# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .bad_request_error_body import BadRequestErrorBody
    from .evm_dex_position_profile import EvmDexPositionProfile
    from .evm_dex_position_profile_metadata import EvmDexPositionProfileMetadata
    from .evm_dex_position_profile_metrics import EvmDexPositionProfileMetrics
    from .evm_dex_position_profile_payload_options import EvmDexPositionProfilePayloadOptions
    from .evm_dex_position_profile_time_window_enum import EvmDexPositionProfileTimeWindowEnum
    from .evm_dex_price import EvmDexPrice
    from .evm_dex_price_candle import EvmDexPriceCandle
    from .evm_dex_price_history import EvmDexPriceHistory
    from .evm_dex_price_snapshot import EvmDexPriceSnapshot
    from .evm_dex_price_stats import EvmDexPriceStats
    from .evm_dex_profile_search_payload_filter import EvmDexProfileSearchPayloadFilter
    from .evm_dex_profile_search_payload_filter_operators import EvmDexProfileSearchPayloadFilterOperators
    from .evm_dex_profile_search_payload_filter_operators_eq import EvmDexProfileSearchPayloadFilterOperatorsEq
    from .evm_dex_profile_search_payload_filter_operators_in_item import EvmDexProfileSearchPayloadFilterOperatorsInItem
    from .evm_dex_profile_search_payload_filter_operators_ne import EvmDexProfileSearchPayloadFilterOperatorsNe
    from .evm_dex_profile_search_payload_filter_operators_nin_item import (
        EvmDexProfileSearchPayloadFilterOperatorsNinItem,
    )
    from .evm_dex_profile_search_payload_query import EvmDexProfileSearchPayloadQuery
    from .evm_dex_profile_search_payload_sort import EvmDexProfileSearchPayloadSort
    from .evm_dex_profile_search_payload_sort_direction_enum import EvmDexProfileSearchPayloadSortDirectionEnum
    from .evm_dex_protocol_field import EvmDexProtocolField
    from .evm_dex_swap import EvmDexSwap
    from .evm_dex_swap_type_enum import EvmDexSwapTypeEnum
    from .evm_dex_token_profile import EvmDexTokenProfile
    from .evm_dex_token_profile_metadata import EvmDexTokenProfileMetadata
    from .evm_dex_token_profile_metrics import EvmDexTokenProfileMetrics
    from .evm_dex_token_profile_payload_options import EvmDexTokenProfilePayloadOptions
    from .evm_dex_token_profile_search_payload_query_field import EvmDexTokenProfileSearchPayloadQueryField
    from .evm_dex_token_profile_search_payload_query_field_targets_enum import (
        EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum,
    )
    from .evm_dex_token_profile_time_window_enum import EvmDexTokenProfileTimeWindowEnum
    from .evm_dex_trade import EvmDexTrade
    from .evm_dex_trade_direction_enum import EvmDexTradeDirectionEnum
    from .evm_dex_trade_position_state_enum import EvmDexTradePositionStateEnum
    from .evm_dex_wallet_profile import EvmDexWalletProfile
    from .evm_dex_wallet_profile_metadata import EvmDexWalletProfileMetadata
    from .evm_dex_wallet_profile_metrics import EvmDexWalletProfileMetrics
    from .evm_dex_wallet_profile_payload_options import EvmDexWalletProfilePayloadOptions
    from .evm_dex_wallet_profile_search_payload_query import EvmDexWalletProfileSearchPayloadQuery
    from .evm_dex_wallet_profile_search_payload_query_targets_enum import (
        EvmDexWalletProfileSearchPayloadQueryTargetsEnum,
    )
    from .evm_dex_wallet_profile_time_window_enum import EvmDexWalletProfileTimeWindowEnum
    from .forbidden_error_body import ForbiddenErrorBody
    from .internal_server_error_body import InternalServerErrorBody
    from .paginated_response import PaginatedResponse
    from .payload_pagination import PayloadPagination
    from .solana_dex_position_profile import SolanaDexPositionProfile
    from .solana_dex_position_profile_labels import SolanaDexPositionProfileLabels
    from .solana_dex_position_profile_metadata import SolanaDexPositionProfileMetadata
    from .solana_dex_position_profile_metrics import SolanaDexPositionProfileMetrics
    from .solana_dex_position_profile_payload_options import SolanaDexPositionProfilePayloadOptions
    from .solana_dex_position_profile_time_window_enum import SolanaDexPositionProfileTimeWindowEnum
    from .solana_dex_price import SolanaDexPrice
    from .solana_dex_price_candle import SolanaDexPriceCandle
    from .solana_dex_price_history import SolanaDexPriceHistory
    from .solana_dex_price_snapshot import SolanaDexPriceSnapshot
    from .solana_dex_price_stats import SolanaDexPriceStats
    from .solana_dex_profile_dynamic_labels import SolanaDexProfileDynamicLabels
    from .solana_dex_profile_search_payload_dynamic_labels import SolanaDexProfileSearchPayloadDynamicLabels
    from .solana_dex_profile_search_payload_filter import SolanaDexProfileSearchPayloadFilter
    from .solana_dex_profile_search_payload_filter_operators import SolanaDexProfileSearchPayloadFilterOperators
    from .solana_dex_profile_search_payload_filter_operators_eq import SolanaDexProfileSearchPayloadFilterOperatorsEq
    from .solana_dex_profile_search_payload_filter_operators_in_item import (
        SolanaDexProfileSearchPayloadFilterOperatorsInItem,
    )
    from .solana_dex_profile_search_payload_filter_operators_ne import SolanaDexProfileSearchPayloadFilterOperatorsNe
    from .solana_dex_profile_search_payload_filter_operators_nin_item import (
        SolanaDexProfileSearchPayloadFilterOperatorsNinItem,
    )
    from .solana_dex_profile_search_payload_query import SolanaDexProfileSearchPayloadQuery
    from .solana_dex_profile_search_payload_sort import SolanaDexProfileSearchPayloadSort
    from .solana_dex_profile_search_payload_sort_direction_enum import SolanaDexProfileSearchPayloadSortDirectionEnum
    from .solana_dex_protocol_field import SolanaDexProtocolField
    from .solana_dex_swap import SolanaDexSwap
    from .solana_dex_swap_type_enum import SolanaDexSwapTypeEnum
    from .solana_dex_token_profile import SolanaDexTokenProfile
    from .solana_dex_token_profile_label_enum import SolanaDexTokenProfileLabelEnum
    from .solana_dex_token_profile_labels import SolanaDexTokenProfileLabels
    from .solana_dex_token_profile_market import SolanaDexTokenProfileMarket
    from .solana_dex_token_profile_metadata import SolanaDexTokenProfileMetadata
    from .solana_dex_token_profile_metrics import SolanaDexTokenProfileMetrics
    from .solana_dex_token_profile_payload_options import SolanaDexTokenProfilePayloadOptions
    from .solana_dex_token_profile_search_payload_query_field import SolanaDexTokenProfileSearchPayloadQueryField
    from .solana_dex_token_profile_search_payload_query_field_targets_enum import (
        SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum,
    )
    from .solana_dex_token_profile_time_window_enum import SolanaDexTokenProfileTimeWindowEnum
    from .solana_dex_trade import SolanaDexTrade
    from .solana_dex_trade_direction_enum import SolanaDexTradeDirectionEnum
    from .solana_dex_trade_position_state_enum import SolanaDexTradePositionStateEnum
    from .solana_dex_wallet_profile import SolanaDexWalletProfile
    from .solana_dex_wallet_profile_identity import SolanaDexWalletProfileIdentity
    from .solana_dex_wallet_profile_label_enum import SolanaDexWalletProfileLabelEnum
    from .solana_dex_wallet_profile_labels import SolanaDexWalletProfileLabels
    from .solana_dex_wallet_profile_metadata import SolanaDexWalletProfileMetadata
    from .solana_dex_wallet_profile_metrics import SolanaDexWalletProfileMetrics
    from .solana_dex_wallet_profile_payload_options import SolanaDexWalletProfilePayloadOptions
    from .solana_dex_wallet_profile_search_payload_query import SolanaDexWalletProfileSearchPayloadQuery
    from .solana_dex_wallet_profile_search_payload_query_targets_enum import (
        SolanaDexWalletProfileSearchPayloadQueryTargetsEnum,
    )
    from .solana_dex_wallet_profile_time_window_enum import SolanaDexWalletProfileTimeWindowEnum
    from .too_many_requests_error_body import TooManyRequestsErrorBody
    from .unauthorized_error_body import UnauthorizedErrorBody
_dynamic_imports: typing.Dict[str, str] = {
    "BadRequestErrorBody": ".bad_request_error_body",
    "EvmDexPositionProfile": ".evm_dex_position_profile",
    "EvmDexPositionProfileMetadata": ".evm_dex_position_profile_metadata",
    "EvmDexPositionProfileMetrics": ".evm_dex_position_profile_metrics",
    "EvmDexPositionProfilePayloadOptions": ".evm_dex_position_profile_payload_options",
    "EvmDexPositionProfileTimeWindowEnum": ".evm_dex_position_profile_time_window_enum",
    "EvmDexPrice": ".evm_dex_price",
    "EvmDexPriceCandle": ".evm_dex_price_candle",
    "EvmDexPriceHistory": ".evm_dex_price_history",
    "EvmDexPriceSnapshot": ".evm_dex_price_snapshot",
    "EvmDexPriceStats": ".evm_dex_price_stats",
    "EvmDexProfileSearchPayloadFilter": ".evm_dex_profile_search_payload_filter",
    "EvmDexProfileSearchPayloadFilterOperators": ".evm_dex_profile_search_payload_filter_operators",
    "EvmDexProfileSearchPayloadFilterOperatorsEq": ".evm_dex_profile_search_payload_filter_operators_eq",
    "EvmDexProfileSearchPayloadFilterOperatorsInItem": ".evm_dex_profile_search_payload_filter_operators_in_item",
    "EvmDexProfileSearchPayloadFilterOperatorsNe": ".evm_dex_profile_search_payload_filter_operators_ne",
    "EvmDexProfileSearchPayloadFilterOperatorsNinItem": ".evm_dex_profile_search_payload_filter_operators_nin_item",
    "EvmDexProfileSearchPayloadQuery": ".evm_dex_profile_search_payload_query",
    "EvmDexProfileSearchPayloadSort": ".evm_dex_profile_search_payload_sort",
    "EvmDexProfileSearchPayloadSortDirectionEnum": ".evm_dex_profile_search_payload_sort_direction_enum",
    "EvmDexProtocolField": ".evm_dex_protocol_field",
    "EvmDexSwap": ".evm_dex_swap",
    "EvmDexSwapTypeEnum": ".evm_dex_swap_type_enum",
    "EvmDexTokenProfile": ".evm_dex_token_profile",
    "EvmDexTokenProfileMetadata": ".evm_dex_token_profile_metadata",
    "EvmDexTokenProfileMetrics": ".evm_dex_token_profile_metrics",
    "EvmDexTokenProfilePayloadOptions": ".evm_dex_token_profile_payload_options",
    "EvmDexTokenProfileSearchPayloadQueryField": ".evm_dex_token_profile_search_payload_query_field",
    "EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum": ".evm_dex_token_profile_search_payload_query_field_targets_enum",
    "EvmDexTokenProfileTimeWindowEnum": ".evm_dex_token_profile_time_window_enum",
    "EvmDexTrade": ".evm_dex_trade",
    "EvmDexTradeDirectionEnum": ".evm_dex_trade_direction_enum",
    "EvmDexTradePositionStateEnum": ".evm_dex_trade_position_state_enum",
    "EvmDexWalletProfile": ".evm_dex_wallet_profile",
    "EvmDexWalletProfileMetadata": ".evm_dex_wallet_profile_metadata",
    "EvmDexWalletProfileMetrics": ".evm_dex_wallet_profile_metrics",
    "EvmDexWalletProfilePayloadOptions": ".evm_dex_wallet_profile_payload_options",
    "EvmDexWalletProfileSearchPayloadQuery": ".evm_dex_wallet_profile_search_payload_query",
    "EvmDexWalletProfileSearchPayloadQueryTargetsEnum": ".evm_dex_wallet_profile_search_payload_query_targets_enum",
    "EvmDexWalletProfileTimeWindowEnum": ".evm_dex_wallet_profile_time_window_enum",
    "ForbiddenErrorBody": ".forbidden_error_body",
    "InternalServerErrorBody": ".internal_server_error_body",
    "PaginatedResponse": ".paginated_response",
    "PayloadPagination": ".payload_pagination",
    "SolanaDexPositionProfile": ".solana_dex_position_profile",
    "SolanaDexPositionProfileLabels": ".solana_dex_position_profile_labels",
    "SolanaDexPositionProfileMetadata": ".solana_dex_position_profile_metadata",
    "SolanaDexPositionProfileMetrics": ".solana_dex_position_profile_metrics",
    "SolanaDexPositionProfilePayloadOptions": ".solana_dex_position_profile_payload_options",
    "SolanaDexPositionProfileTimeWindowEnum": ".solana_dex_position_profile_time_window_enum",
    "SolanaDexPrice": ".solana_dex_price",
    "SolanaDexPriceCandle": ".solana_dex_price_candle",
    "SolanaDexPriceHistory": ".solana_dex_price_history",
    "SolanaDexPriceSnapshot": ".solana_dex_price_snapshot",
    "SolanaDexPriceStats": ".solana_dex_price_stats",
    "SolanaDexProfileDynamicLabels": ".solana_dex_profile_dynamic_labels",
    "SolanaDexProfileSearchPayloadDynamicLabels": ".solana_dex_profile_search_payload_dynamic_labels",
    "SolanaDexProfileSearchPayloadFilter": ".solana_dex_profile_search_payload_filter",
    "SolanaDexProfileSearchPayloadFilterOperators": ".solana_dex_profile_search_payload_filter_operators",
    "SolanaDexProfileSearchPayloadFilterOperatorsEq": ".solana_dex_profile_search_payload_filter_operators_eq",
    "SolanaDexProfileSearchPayloadFilterOperatorsInItem": ".solana_dex_profile_search_payload_filter_operators_in_item",
    "SolanaDexProfileSearchPayloadFilterOperatorsNe": ".solana_dex_profile_search_payload_filter_operators_ne",
    "SolanaDexProfileSearchPayloadFilterOperatorsNinItem": ".solana_dex_profile_search_payload_filter_operators_nin_item",
    "SolanaDexProfileSearchPayloadQuery": ".solana_dex_profile_search_payload_query",
    "SolanaDexProfileSearchPayloadSort": ".solana_dex_profile_search_payload_sort",
    "SolanaDexProfileSearchPayloadSortDirectionEnum": ".solana_dex_profile_search_payload_sort_direction_enum",
    "SolanaDexProtocolField": ".solana_dex_protocol_field",
    "SolanaDexSwap": ".solana_dex_swap",
    "SolanaDexSwapTypeEnum": ".solana_dex_swap_type_enum",
    "SolanaDexTokenProfile": ".solana_dex_token_profile",
    "SolanaDexTokenProfileLabelEnum": ".solana_dex_token_profile_label_enum",
    "SolanaDexTokenProfileLabels": ".solana_dex_token_profile_labels",
    "SolanaDexTokenProfileMarket": ".solana_dex_token_profile_market",
    "SolanaDexTokenProfileMetadata": ".solana_dex_token_profile_metadata",
    "SolanaDexTokenProfileMetrics": ".solana_dex_token_profile_metrics",
    "SolanaDexTokenProfilePayloadOptions": ".solana_dex_token_profile_payload_options",
    "SolanaDexTokenProfileSearchPayloadQueryField": ".solana_dex_token_profile_search_payload_query_field",
    "SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum": ".solana_dex_token_profile_search_payload_query_field_targets_enum",
    "SolanaDexTokenProfileTimeWindowEnum": ".solana_dex_token_profile_time_window_enum",
    "SolanaDexTrade": ".solana_dex_trade",
    "SolanaDexTradeDirectionEnum": ".solana_dex_trade_direction_enum",
    "SolanaDexTradePositionStateEnum": ".solana_dex_trade_position_state_enum",
    "SolanaDexWalletProfile": ".solana_dex_wallet_profile",
    "SolanaDexWalletProfileIdentity": ".solana_dex_wallet_profile_identity",
    "SolanaDexWalletProfileLabelEnum": ".solana_dex_wallet_profile_label_enum",
    "SolanaDexWalletProfileLabels": ".solana_dex_wallet_profile_labels",
    "SolanaDexWalletProfileMetadata": ".solana_dex_wallet_profile_metadata",
    "SolanaDexWalletProfileMetrics": ".solana_dex_wallet_profile_metrics",
    "SolanaDexWalletProfilePayloadOptions": ".solana_dex_wallet_profile_payload_options",
    "SolanaDexWalletProfileSearchPayloadQuery": ".solana_dex_wallet_profile_search_payload_query",
    "SolanaDexWalletProfileSearchPayloadQueryTargetsEnum": ".solana_dex_wallet_profile_search_payload_query_targets_enum",
    "SolanaDexWalletProfileTimeWindowEnum": ".solana_dex_wallet_profile_time_window_enum",
    "TooManyRequestsErrorBody": ".too_many_requests_error_body",
    "UnauthorizedErrorBody": ".unauthorized_error_body",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BadRequestErrorBody",
    "EvmDexPositionProfile",
    "EvmDexPositionProfileMetadata",
    "EvmDexPositionProfileMetrics",
    "EvmDexPositionProfilePayloadOptions",
    "EvmDexPositionProfileTimeWindowEnum",
    "EvmDexPrice",
    "EvmDexPriceCandle",
    "EvmDexPriceHistory",
    "EvmDexPriceSnapshot",
    "EvmDexPriceStats",
    "EvmDexProfileSearchPayloadFilter",
    "EvmDexProfileSearchPayloadFilterOperators",
    "EvmDexProfileSearchPayloadFilterOperatorsEq",
    "EvmDexProfileSearchPayloadFilterOperatorsInItem",
    "EvmDexProfileSearchPayloadFilterOperatorsNe",
    "EvmDexProfileSearchPayloadFilterOperatorsNinItem",
    "EvmDexProfileSearchPayloadQuery",
    "EvmDexProfileSearchPayloadSort",
    "EvmDexProfileSearchPayloadSortDirectionEnum",
    "EvmDexProtocolField",
    "EvmDexSwap",
    "EvmDexSwapTypeEnum",
    "EvmDexTokenProfile",
    "EvmDexTokenProfileMetadata",
    "EvmDexTokenProfileMetrics",
    "EvmDexTokenProfilePayloadOptions",
    "EvmDexTokenProfileSearchPayloadQueryField",
    "EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum",
    "EvmDexTokenProfileTimeWindowEnum",
    "EvmDexTrade",
    "EvmDexTradeDirectionEnum",
    "EvmDexTradePositionStateEnum",
    "EvmDexWalletProfile",
    "EvmDexWalletProfileMetadata",
    "EvmDexWalletProfileMetrics",
    "EvmDexWalletProfilePayloadOptions",
    "EvmDexWalletProfileSearchPayloadQuery",
    "EvmDexWalletProfileSearchPayloadQueryTargetsEnum",
    "EvmDexWalletProfileTimeWindowEnum",
    "ForbiddenErrorBody",
    "InternalServerErrorBody",
    "PaginatedResponse",
    "PayloadPagination",
    "SolanaDexPositionProfile",
    "SolanaDexPositionProfileLabels",
    "SolanaDexPositionProfileMetadata",
    "SolanaDexPositionProfileMetrics",
    "SolanaDexPositionProfilePayloadOptions",
    "SolanaDexPositionProfileTimeWindowEnum",
    "SolanaDexPrice",
    "SolanaDexPriceCandle",
    "SolanaDexPriceHistory",
    "SolanaDexPriceSnapshot",
    "SolanaDexPriceStats",
    "SolanaDexProfileDynamicLabels",
    "SolanaDexProfileSearchPayloadDynamicLabels",
    "SolanaDexProfileSearchPayloadFilter",
    "SolanaDexProfileSearchPayloadFilterOperators",
    "SolanaDexProfileSearchPayloadFilterOperatorsEq",
    "SolanaDexProfileSearchPayloadFilterOperatorsInItem",
    "SolanaDexProfileSearchPayloadFilterOperatorsNe",
    "SolanaDexProfileSearchPayloadFilterOperatorsNinItem",
    "SolanaDexProfileSearchPayloadQuery",
    "SolanaDexProfileSearchPayloadSort",
    "SolanaDexProfileSearchPayloadSortDirectionEnum",
    "SolanaDexProtocolField",
    "SolanaDexSwap",
    "SolanaDexSwapTypeEnum",
    "SolanaDexTokenProfile",
    "SolanaDexTokenProfileLabelEnum",
    "SolanaDexTokenProfileLabels",
    "SolanaDexTokenProfileMarket",
    "SolanaDexTokenProfileMetadata",
    "SolanaDexTokenProfileMetrics",
    "SolanaDexTokenProfilePayloadOptions",
    "SolanaDexTokenProfileSearchPayloadQueryField",
    "SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum",
    "SolanaDexTokenProfileTimeWindowEnum",
    "SolanaDexTrade",
    "SolanaDexTradeDirectionEnum",
    "SolanaDexTradePositionStateEnum",
    "SolanaDexWalletProfile",
    "SolanaDexWalletProfileIdentity",
    "SolanaDexWalletProfileLabelEnum",
    "SolanaDexWalletProfileLabels",
    "SolanaDexWalletProfileMetadata",
    "SolanaDexWalletProfileMetrics",
    "SolanaDexWalletProfilePayloadOptions",
    "SolanaDexWalletProfileSearchPayloadQuery",
    "SolanaDexWalletProfileSearchPayloadQueryTargetsEnum",
    "SolanaDexWalletProfileTimeWindowEnum",
    "TooManyRequestsErrorBody",
    "UnauthorizedErrorBody",
]
