# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evm_dex_protocol_field import EvmDexProtocolField
from .evm_dex_swap_type_enum import EvmDexSwapTypeEnum
from .evm_dex_trade_direction_enum import EvmDexTradeDirectionEnum
from .evm_dex_trade_position_state_enum import EvmDexTradePositionStateEnum


class EvmDexTrade(UniversalBaseModel):
    id: typing.Optional[int] = None
    chain_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Numeric EVM chain ID the record belongs to.
    """

    protocol: typing.Optional[EvmDexProtocolField] = None
    swap_type: typing.Optional[EvmDexSwapTypeEnum] = None
    wallet_address: typing.Optional[str] = None
    token_address: typing.Optional[str] = None
    quote_address: typing.Optional[str] = None
    position_address: typing.Optional[str] = None
    direction: typing.Optional[EvmDexTradeDirectionEnum] = None
    position_state: typing.Optional[EvmDexTradePositionStateEnum] = None
    token_amount: typing.Optional[float] = None
    quote_amount: typing.Optional[float] = None
    native_amount: typing.Optional[float] = None
    usd_amount: typing.Optional[float] = None
    pre_token_balance: typing.Optional[float] = None
    post_token_balance: typing.Optional[float] = None
    token_price: typing.Optional[float] = None
    quote_price: typing.Optional[float] = None
    token_mcap: typing.Optional[float] = None
    block_number: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None
    tx_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
