# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evm_dex_position_profile_time_window_enum import EvmDexPositionProfileTimeWindowEnum


class EvmDexPositionProfilePayloadOptions(UniversalBaseModel):
    """
    Controls which optional sections are included in each returned position profile.
    """

    include_metadata: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, includes the `metadata` object in each returned profile.
    """

    include_metrics: typing.Optional[typing.List[EvmDexPositionProfileTimeWindowEnum]] = pydantic.Field(default=None)
    """
    Time windows for which metrics should be included. Windows not listed are omitted from the response.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
