# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class EvmDexPriceStats(UniversalBaseModel):
    token_address: typing.Optional[str] = None
    pool_address: typing.Optional[str] = None
    usd_price: typing.Optional[float] = None
    usd_price_change5m: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_price_change_5m"), pydantic.Field(alias="usd_price_change_5m")
    ] = None
    usd_price_change1h: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_price_change_1h"), pydantic.Field(alias="usd_price_change_1h")
    ] = None
    usd_price_change6h: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_price_change_6h"), pydantic.Field(alias="usd_price_change_6h")
    ] = None
    usd_price_change12h: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_price_change_12h"),
        pydantic.Field(alias="usd_price_change_12h"),
    ] = None
    usd_price_change1d: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_price_change_1d"), pydantic.Field(alias="usd_price_change_1d")
    ] = None
    usd_price_change7d: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_price_change_7d"), pydantic.Field(alias="usd_price_change_7d")
    ] = None
    usd_price_change30d: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_price_change_30d"),
        pydantic.Field(alias="usd_price_change_30d"),
    ] = None
    usd_volume5m: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_5m"), pydantic.Field(alias="usd_volume_5m")
    ] = None
    usd_volume1h: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_1h"), pydantic.Field(alias="usd_volume_1h")
    ] = None
    usd_volume6h: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_6h"), pydantic.Field(alias="usd_volume_6h")
    ] = None
    usd_volume12h: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_12h"), pydantic.Field(alias="usd_volume_12h")
    ] = None
    usd_volume1d: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_1d"), pydantic.Field(alias="usd_volume_1d")
    ] = None
    usd_volume7d: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_7d"), pydantic.Field(alias="usd_volume_7d")
    ] = None
    usd_volume30d: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="usd_volume_30d"), pydantic.Field(alias="usd_volume_30d")
    ] = None
    usd_volume_change5m: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_5m"),
        pydantic.Field(alias="usd_volume_change_5m"),
    ] = None
    usd_volume_change1h: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_1h"),
        pydantic.Field(alias="usd_volume_change_1h"),
    ] = None
    usd_volume_change6h: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_6h"),
        pydantic.Field(alias="usd_volume_change_6h"),
    ] = None
    usd_volume_change12h: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_12h"),
        pydantic.Field(alias="usd_volume_change_12h"),
    ] = None
    usd_volume_change1d: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_1d"),
        pydantic.Field(alias="usd_volume_change_1d"),
    ] = None
    usd_volume_change7d: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_7d"),
        pydantic.Field(alias="usd_volume_change_7d"),
    ] = None
    usd_volume_change30d: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="usd_volume_change_30d"),
        pydantic.Field(alias="usd_volume_change_30d"),
    ] = None
    block_number: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
