# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evm_dex_wallet_profile_search_payload_query_targets_enum import EvmDexWalletProfileSearchPayloadQueryTargetsEnum


class EvmDexWalletProfileSearchPayloadQuery(UniversalBaseModel):
    fields: typing.Optional[typing.List[EvmDexWalletProfileSearchPayloadQueryTargetsEnum]] = pydantic.Field(
        default=None
    )
    """
    Wallet profile fields that the text value should be matched against.
    """

    text: str = pydantic.Field()
    """
    Text value to match against the selected fields.
    """

    fuzzy: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, matches values that are approximately similar to `text`, allowing for minor typos and variations.
    """

    autocomplete: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, matches values that start with `text`, useful for type-ahead lookups.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
