# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .evm_dex_profile_search_payload_filter_operators_eq import EvmDexProfileSearchPayloadFilterOperatorsEq
from .evm_dex_profile_search_payload_filter_operators_in_item import EvmDexProfileSearchPayloadFilterOperatorsInItem
from .evm_dex_profile_search_payload_filter_operators_ne import EvmDexProfileSearchPayloadFilterOperatorsNe
from .evm_dex_profile_search_payload_filter_operators_nin_item import EvmDexProfileSearchPayloadFilterOperatorsNinItem


class EvmDexProfileSearchPayloadFilterOperators(UniversalBaseModel):
    """
    Comparison operators applied to a single field. At least one operator must be provided.
    """

    eq: typing_extensions.Annotated[
        typing.Optional[EvmDexProfileSearchPayloadFilterOperatorsEq],
        FieldMetadata(alias="$eq"),
        pydantic.Field(alias="$eq", description="Equal to."),
    ] = None
    ne: typing_extensions.Annotated[
        typing.Optional[EvmDexProfileSearchPayloadFilterOperatorsNe],
        FieldMetadata(alias="$ne"),
        pydantic.Field(alias="$ne", description="Not equal to."),
    ] = None
    gt: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="$gt"), pydantic.Field(alias="$gt", description="Greater than.")
    ] = None
    lt: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="$lt"), pydantic.Field(alias="$lt", description="Less than.")
    ] = None
    gte: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="$gte"),
        pydantic.Field(alias="$gte", description="Greater than or equal to."),
    ] = None
    lte: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="$lte"),
        pydantic.Field(alias="$lte", description="Less than or equal to."),
    ] = None
    in_: typing_extensions.Annotated[
        typing.Optional[typing.List[EvmDexProfileSearchPayloadFilterOperatorsInItem]],
        FieldMetadata(alias="$in"),
        pydantic.Field(alias="$in", description="In the list."),
    ] = None
    nin: typing_extensions.Annotated[
        typing.Optional[typing.List[EvmDexProfileSearchPayloadFilterOperatorsNinItem]],
        FieldMetadata(alias="$nin"),
        pydantic.Field(alias="$nin", description="Not in the list."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
