# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evm_dex_price_snapshot import EvmDexPriceSnapshot


class EvmDexPriceHistory(UniversalBaseModel):
    token_address: typing.Optional[str] = None
    pool_address: typing.Optional[str] = None
    prices: typing.Optional[typing.List[EvmDexPriceSnapshot]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
