# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EvmDexPrice(UniversalBaseModel):
    chain_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Numeric EVM chain ID the record belongs to.
    """

    token_address: typing.Optional[str] = None
    pool_address: typing.Optional[str] = None
    usd_price: typing.Optional[float] = None
    block_number: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
