# This file was auto-generated by Fern from our API Definition.

EvmDexProtocolField = str
"""
Refer to [Data Sources](/documentation/evm/dex/overview#data-sources) for the list of supported protocols.
"""
