# This file was auto-generated by Fern from our API Definition.

SolanaDexProtocolField = str
"""
Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
"""
