# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SolanaDexProfileSearchPayloadQuery(UniversalBaseModel):
    """
    Full-text query used to match profiles by a text value against one or more fields.
    """

    text: str = pydantic.Field()
    """
    Text value to match against the selected fields.
    """

    fields: typing.List[str] = pydantic.Field()
    """
    Fields that the text value should be matched against.
    """

    fuzzy: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, matches values that are approximately similar to `text`, allowing for minor typos and variations.
    """

    autocomplete: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, matches values that start with `text`, useful for type-ahead lookups.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
