# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_position_profile_labels import SolanaDexPositionProfileLabels
from .solana_dex_position_profile_metadata import SolanaDexPositionProfileMetadata
from .solana_dex_position_profile_metrics import SolanaDexPositionProfileMetrics
from .solana_dex_profile_dynamic_labels import SolanaDexProfileDynamicLabels


class SolanaDexPositionProfile(UniversalBaseModel):
    updated_at: typing.Optional[dt.datetime] = None
    synced_at: typing.Optional[dt.datetime] = None
    position_address: typing.Optional[str] = None
    wallet_address: typing.Optional[str] = None
    token_address: typing.Optional[str] = None
    labels: typing.Optional[SolanaDexPositionProfileLabels] = None
    dynamic_labels: typing.Optional[SolanaDexProfileDynamicLabels] = None
    metadata: typing.Optional[SolanaDexPositionProfileMetadata] = None
    metrics: typing.Optional[typing.Dict[str, SolanaDexPositionProfileMetrics]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
