# This file was auto-generated by Fern from our API Definition.

import typing

SolanaDexWalletProfileLabelEnum = typing.Union[
    typing.Literal["kol", "trencher", "conviction", "smart", "whale", "degen", "sniper", "swing", "holder"], typing.Any
]
