# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SolanaDexTokenProfileMarket(UniversalBaseModel):
    fdv: typing.Optional[float] = None
    market_cap: typing.Optional[float] = None
    price: typing.Optional[float] = None
    liquidity: typing.Optional[float] = None
    holders: typing.Optional[int] = None
    total_supply: typing.Optional[float] = None
    circulating_supply: typing.Optional[float] = None
    top_holdings: typing.Optional[float] = None
    dev_holdings: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
