# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        SolanaAssetsBalanceChangeMessage,
        SolanaAssetsBalanceChangeTypeEnum,
        SolanaAssetsTransferMessage,
        SolanaAssetsTransferTypeEnum,
        SolanaDexPoolMessage,
        SolanaDexPoolMessageEventTypeEnum,
        SolanaDexPoolMessageVault,
        SolanaDexPriceMessage,
        SolanaDexSwapMessage,
        SolanaDexSwapTypeEnum,
        SolanaDexTokenProfileLabelEnum,
        SolanaDexTokenProfileMarket,
        SolanaDexTokenProfileMessage,
        SolanaDexTokenProfileMetadata,
        SolanaDexTokenProfileMetrics,
        SolanaDexTradeDirectionEnum,
        SolanaDexTradeMessage,
        SolanaDexTradePositionStateEnum,
        SolanaDexWalletProfileIdentity,
        SolanaDexWalletProfileLabelEnum,
        SolanaDexWalletProfileMessage,
        SolanaDexWalletProfileMetadata,
        SolanaDexWalletProfileMetrics,
        SubscribePayload,
        SubscribePayloadParams,
        SubscriptionMessage,
        SubscriptionMessageData,
        SubscriptionMethodEnum,
        SubscriptionTopicEnum,
        UnsubscribePayload,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "SolanaAssetsBalanceChangeMessage": ".types",
    "SolanaAssetsBalanceChangeTypeEnum": ".types",
    "SolanaAssetsTransferMessage": ".types",
    "SolanaAssetsTransferTypeEnum": ".types",
    "SolanaDexPoolMessage": ".types",
    "SolanaDexPoolMessageEventTypeEnum": ".types",
    "SolanaDexPoolMessageVault": ".types",
    "SolanaDexPriceMessage": ".types",
    "SolanaDexSwapMessage": ".types",
    "SolanaDexSwapTypeEnum": ".types",
    "SolanaDexTokenProfileLabelEnum": ".types",
    "SolanaDexTokenProfileMarket": ".types",
    "SolanaDexTokenProfileMessage": ".types",
    "SolanaDexTokenProfileMetadata": ".types",
    "SolanaDexTokenProfileMetrics": ".types",
    "SolanaDexTradeDirectionEnum": ".types",
    "SolanaDexTradeMessage": ".types",
    "SolanaDexTradePositionStateEnum": ".types",
    "SolanaDexWalletProfileIdentity": ".types",
    "SolanaDexWalletProfileLabelEnum": ".types",
    "SolanaDexWalletProfileMessage": ".types",
    "SolanaDexWalletProfileMetadata": ".types",
    "SolanaDexWalletProfileMetrics": ".types",
    "SubscribePayload": ".types",
    "SubscribePayloadParams": ".types",
    "SubscriptionMessage": ".types",
    "SubscriptionMessageData": ".types",
    "SubscriptionMethodEnum": ".types",
    "SubscriptionTopicEnum": ".types",
    "UnsubscribePayload": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SolanaAssetsBalanceChangeMessage",
    "SolanaAssetsBalanceChangeTypeEnum",
    "SolanaAssetsTransferMessage",
    "SolanaAssetsTransferTypeEnum",
    "SolanaDexPoolMessage",
    "SolanaDexPoolMessageEventTypeEnum",
    "SolanaDexPoolMessageVault",
    "SolanaDexPriceMessage",
    "SolanaDexSwapMessage",
    "SolanaDexSwapTypeEnum",
    "SolanaDexTokenProfileLabelEnum",
    "SolanaDexTokenProfileMarket",
    "SolanaDexTokenProfileMessage",
    "SolanaDexTokenProfileMetadata",
    "SolanaDexTokenProfileMetrics",
    "SolanaDexTradeDirectionEnum",
    "SolanaDexTradeMessage",
    "SolanaDexTradePositionStateEnum",
    "SolanaDexWalletProfileIdentity",
    "SolanaDexWalletProfileLabelEnum",
    "SolanaDexWalletProfileMessage",
    "SolanaDexWalletProfileMetadata",
    "SolanaDexWalletProfileMetrics",
    "SubscribePayload",
    "SubscribePayloadParams",
    "SubscriptionMessage",
    "SubscriptionMessageData",
    "SubscriptionMethodEnum",
    "SubscriptionTopicEnum",
    "UnsubscribePayload",
]
