# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .subscribe_token_trades import SubscribeTokenTrades
    from .subscribe_token_trades_params import SubscribeTokenTradesParams
    from .subscribe_wallet_trades import SubscribeWalletTrades
    from .subscribe_wallet_trades_params import SubscribeWalletTradesParams
    from .token_trades_subscription_message import TokenTradesSubscriptionMessage
    from .token_trades_subscription_message_data import TokenTradesSubscriptionMessageData
    from .token_trades_subscription_message_data_direction import TokenTradesSubscriptionMessageDataDirection
    from .token_trades_subscription_message_data_position_state import TokenTradesSubscriptionMessageDataPositionState
    from .token_trades_subscription_message_data_swap_type import TokenTradesSubscriptionMessageDataSwapType
    from .unsubscribe_token_trades import UnsubscribeTokenTrades
    from .unsubscribe_token_trades_params import UnsubscribeTokenTradesParams
    from .unsubscribe_wallet_trades import UnsubscribeWalletTrades
    from .unsubscribe_wallet_trades_params import UnsubscribeWalletTradesParams
    from .wallet_trades_subscription_message import WalletTradesSubscriptionMessage
    from .wallet_trades_subscription_message_data import WalletTradesSubscriptionMessageData
    from .wallet_trades_subscription_message_data_direction import WalletTradesSubscriptionMessageDataDirection
    from .wallet_trades_subscription_message_data_position_state import WalletTradesSubscriptionMessageDataPositionState
    from .wallet_trades_subscription_message_data_swap_type import WalletTradesSubscriptionMessageDataSwapType
_dynamic_imports: typing.Dict[str, str] = {
    "SubscribeTokenTrades": ".subscribe_token_trades",
    "SubscribeTokenTradesParams": ".subscribe_token_trades_params",
    "SubscribeWalletTrades": ".subscribe_wallet_trades",
    "SubscribeWalletTradesParams": ".subscribe_wallet_trades_params",
    "TokenTradesSubscriptionMessage": ".token_trades_subscription_message",
    "TokenTradesSubscriptionMessageData": ".token_trades_subscription_message_data",
    "TokenTradesSubscriptionMessageDataDirection": ".token_trades_subscription_message_data_direction",
    "TokenTradesSubscriptionMessageDataPositionState": ".token_trades_subscription_message_data_position_state",
    "TokenTradesSubscriptionMessageDataSwapType": ".token_trades_subscription_message_data_swap_type",
    "UnsubscribeTokenTrades": ".unsubscribe_token_trades",
    "UnsubscribeTokenTradesParams": ".unsubscribe_token_trades_params",
    "UnsubscribeWalletTrades": ".unsubscribe_wallet_trades",
    "UnsubscribeWalletTradesParams": ".unsubscribe_wallet_trades_params",
    "WalletTradesSubscriptionMessage": ".wallet_trades_subscription_message",
    "WalletTradesSubscriptionMessageData": ".wallet_trades_subscription_message_data",
    "WalletTradesSubscriptionMessageDataDirection": ".wallet_trades_subscription_message_data_direction",
    "WalletTradesSubscriptionMessageDataPositionState": ".wallet_trades_subscription_message_data_position_state",
    "WalletTradesSubscriptionMessageDataSwapType": ".wallet_trades_subscription_message_data_swap_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SubscribeTokenTrades",
    "SubscribeTokenTradesParams",
    "SubscribeWalletTrades",
    "SubscribeWalletTradesParams",
    "TokenTradesSubscriptionMessage",
    "TokenTradesSubscriptionMessageData",
    "TokenTradesSubscriptionMessageDataDirection",
    "TokenTradesSubscriptionMessageDataPositionState",
    "TokenTradesSubscriptionMessageDataSwapType",
    "UnsubscribeTokenTrades",
    "UnsubscribeTokenTradesParams",
    "UnsubscribeWalletTrades",
    "UnsubscribeWalletTradesParams",
    "WalletTradesSubscriptionMessage",
    "WalletTradesSubscriptionMessageData",
    "WalletTradesSubscriptionMessageDataDirection",
    "WalletTradesSubscriptionMessageDataPositionState",
    "WalletTradesSubscriptionMessageDataSwapType",
]
