# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .token_trades_subscription_message_data import TokenTradesSubscriptionMessageData


class TokenTradesSubscriptionMessage(UniversalBaseModel):
    topic: typing.Optional[str] = None
    data: typing.Optional[TokenTradesSubscriptionMessageData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
