# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .solana_assets_balance_change_message import SolanaAssetsBalanceChangeMessage
    from .solana_assets_balance_change_type_enum import SolanaAssetsBalanceChangeTypeEnum
    from .solana_assets_transfer_message import SolanaAssetsTransferMessage
    from .solana_assets_transfer_type_enum import SolanaAssetsTransferTypeEnum
    from .solana_dex_pool_message import SolanaDexPoolMessage
    from .solana_dex_pool_message_event_type_enum import SolanaDexPoolMessageEventTypeEnum
    from .solana_dex_pool_message_vault import SolanaDexPoolMessageVault
    from .solana_dex_price_message import SolanaDexPriceMessage
    from .solana_dex_swap_message import SolanaDexSwapMessage
    from .solana_dex_swap_type_enum import SolanaDexSwapTypeEnum
    from .solana_dex_token_profile_label_enum import SolanaDexTokenProfileLabelEnum
    from .solana_dex_token_profile_market import SolanaDexTokenProfileMarket
    from .solana_dex_token_profile_message import SolanaDexTokenProfileMessage
    from .solana_dex_token_profile_metadata import SolanaDexTokenProfileMetadata
    from .solana_dex_token_profile_metrics import SolanaDexTokenProfileMetrics
    from .solana_dex_trade_direction_enum import SolanaDexTradeDirectionEnum
    from .solana_dex_trade_message import SolanaDexTradeMessage
    from .solana_dex_trade_position_state_enum import SolanaDexTradePositionStateEnum
    from .solana_dex_wallet_profile_identity import SolanaDexWalletProfileIdentity
    from .solana_dex_wallet_profile_label_enum import SolanaDexWalletProfileLabelEnum
    from .solana_dex_wallet_profile_message import SolanaDexWalletProfileMessage
    from .solana_dex_wallet_profile_metadata import SolanaDexWalletProfileMetadata
    from .solana_dex_wallet_profile_metrics import SolanaDexWalletProfileMetrics
    from .subscribe_payload import SubscribePayload
    from .subscribe_payload_params import SubscribePayloadParams
    from .subscription_message import SubscriptionMessage
    from .subscription_message_data import SubscriptionMessageData
    from .subscription_method_enum import SubscriptionMethodEnum
    from .subscription_topic_enum import SubscriptionTopicEnum
    from .unsubscribe_payload import UnsubscribePayload
_dynamic_imports: typing.Dict[str, str] = {
    "SolanaAssetsBalanceChangeMessage": ".solana_assets_balance_change_message",
    "SolanaAssetsBalanceChangeTypeEnum": ".solana_assets_balance_change_type_enum",
    "SolanaAssetsTransferMessage": ".solana_assets_transfer_message",
    "SolanaAssetsTransferTypeEnum": ".solana_assets_transfer_type_enum",
    "SolanaDexPoolMessage": ".solana_dex_pool_message",
    "SolanaDexPoolMessageEventTypeEnum": ".solana_dex_pool_message_event_type_enum",
    "SolanaDexPoolMessageVault": ".solana_dex_pool_message_vault",
    "SolanaDexPriceMessage": ".solana_dex_price_message",
    "SolanaDexSwapMessage": ".solana_dex_swap_message",
    "SolanaDexSwapTypeEnum": ".solana_dex_swap_type_enum",
    "SolanaDexTokenProfileLabelEnum": ".solana_dex_token_profile_label_enum",
    "SolanaDexTokenProfileMarket": ".solana_dex_token_profile_market",
    "SolanaDexTokenProfileMessage": ".solana_dex_token_profile_message",
    "SolanaDexTokenProfileMetadata": ".solana_dex_token_profile_metadata",
    "SolanaDexTokenProfileMetrics": ".solana_dex_token_profile_metrics",
    "SolanaDexTradeDirectionEnum": ".solana_dex_trade_direction_enum",
    "SolanaDexTradeMessage": ".solana_dex_trade_message",
    "SolanaDexTradePositionStateEnum": ".solana_dex_trade_position_state_enum",
    "SolanaDexWalletProfileIdentity": ".solana_dex_wallet_profile_identity",
    "SolanaDexWalletProfileLabelEnum": ".solana_dex_wallet_profile_label_enum",
    "SolanaDexWalletProfileMessage": ".solana_dex_wallet_profile_message",
    "SolanaDexWalletProfileMetadata": ".solana_dex_wallet_profile_metadata",
    "SolanaDexWalletProfileMetrics": ".solana_dex_wallet_profile_metrics",
    "SubscribePayload": ".subscribe_payload",
    "SubscribePayloadParams": ".subscribe_payload_params",
    "SubscriptionMessage": ".subscription_message",
    "SubscriptionMessageData": ".subscription_message_data",
    "SubscriptionMethodEnum": ".subscription_method_enum",
    "SubscriptionTopicEnum": ".subscription_topic_enum",
    "UnsubscribePayload": ".unsubscribe_payload",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SolanaAssetsBalanceChangeMessage",
    "SolanaAssetsBalanceChangeTypeEnum",
    "SolanaAssetsTransferMessage",
    "SolanaAssetsTransferTypeEnum",
    "SolanaDexPoolMessage",
    "SolanaDexPoolMessageEventTypeEnum",
    "SolanaDexPoolMessageVault",
    "SolanaDexPriceMessage",
    "SolanaDexSwapMessage",
    "SolanaDexSwapTypeEnum",
    "SolanaDexTokenProfileLabelEnum",
    "SolanaDexTokenProfileMarket",
    "SolanaDexTokenProfileMessage",
    "SolanaDexTokenProfileMetadata",
    "SolanaDexTokenProfileMetrics",
    "SolanaDexTradeDirectionEnum",
    "SolanaDexTradeMessage",
    "SolanaDexTradePositionStateEnum",
    "SolanaDexWalletProfileIdentity",
    "SolanaDexWalletProfileLabelEnum",
    "SolanaDexWalletProfileMessage",
    "SolanaDexWalletProfileMetadata",
    "SolanaDexWalletProfileMetrics",
    "SubscribePayload",
    "SubscribePayloadParams",
    "SubscriptionMessage",
    "SubscriptionMessageData",
    "SubscriptionMethodEnum",
    "SubscriptionTopicEnum",
    "UnsubscribePayload",
]
