# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evm_dex_pool_message_event_type_enum import EvmDexPoolMessageEventTypeEnum
from .evm_dex_pool_message_vault import EvmDexPoolMessageVault


class EvmDexPoolMessage(UniversalBaseModel):
    chain_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Numeric EVM chain ID the record belongs to.
    """

    protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Refer to [Data Sources](/documentation/evm/dex/overview#data-sources) for the list of supported protocols.
    """

    event_type: typing.Optional[EvmDexPoolMessageEventTypeEnum] = None
    pool_address: typing.Optional[str] = None
    vaults: typing.Optional[typing.List[EvmDexPoolMessageVault]] = None
    block_number: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None
    tx_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
