# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evm_dex_wallet_profile_metadata import EvmDexWalletProfileMetadata
from .evm_dex_wallet_profile_metrics import EvmDexWalletProfileMetrics


class EvmDexWalletProfileMessage(UniversalBaseModel):
    updated_at: typing.Optional[dt.datetime] = None
    synced_at: typing.Optional[dt.datetime] = None
    chain_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Numeric EVM chain ID the record belongs to.
    """

    wallet_address: typing.Optional[str] = None
    metadata: typing.Optional[EvmDexWalletProfileMetadata] = None
    metrics: typing.Optional[typing.Dict[str, EvmDexWalletProfileMetrics]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
