# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_swap_type_enum import SolanaDexSwapTypeEnum


class SolanaDexSwapMessage(UniversalBaseModel):
    id: typing.Optional[int] = None
    swap_type: typing.Optional[SolanaDexSwapTypeEnum] = None
    protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
    """

    wallet_address: typing.Optional[str] = None
    token_address_in: typing.Optional[str] = None
    token_address_out: typing.Optional[str] = None
    token_amount_in: typing.Optional[float] = None
    token_amount_out: typing.Optional[float] = None
    token_price_in: typing.Optional[float] = None
    token_price_out: typing.Optional[float] = None
    pre_token_balance_in: typing.Optional[float] = None
    pre_token_balance_out: typing.Optional[float] = None
    post_token_balance_in: typing.Optional[float] = None
    post_token_balance_out: typing.Optional[float] = None
    usd_amount_in: typing.Optional[float] = None
    usd_amount_out: typing.Optional[float] = None
    block_slot: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None
    tx_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
