# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SolanaDexWalletProfileMetrics(UniversalBaseModel):
    risk_score: typing.Optional[float] = None
    consistency_score: typing.Optional[float] = None
    largest_win: typing.Optional[float] = None
    largest_loss: typing.Optional[float] = None
    max_consecutive_wins: typing.Optional[int] = None
    max_consecutive_losses: typing.Optional[int] = None
    avg_buy_size: typing.Optional[float] = None
    avg_sell_size: typing.Optional[float] = None
    avg_buy_mcap: typing.Optional[float] = None
    avg_sell_mcap: typing.Optional[float] = None
    avg_daily_pnl: typing.Optional[float] = None
    avg_daily_roi: typing.Optional[float] = None
    avg_daily_trade_count: typing.Optional[int] = None
    avg_daily_traded_tokens: typing.Optional[int] = None
    avg_daily_volume: typing.Optional[float] = None
    avg_holding_duration: typing.Optional[int] = None
    avg_trade_delta: typing.Optional[int] = None
    avg_pnl: typing.Optional[float] = None
    avg_roi: typing.Optional[float] = None
    avg_token_pnl: typing.Optional[float] = None
    avg_token_roi: typing.Optional[float] = None
    token_roi_distribution: typing.Optional[typing.Dict[str, int]] = None
    trade_count: typing.Optional[int] = None
    buy_count: typing.Optional[int] = None
    sell_count: typing.Optional[int] = None
    position_count: typing.Optional[int] = None
    win_count: typing.Optional[int] = None
    loss_count: typing.Optional[int] = None
    pnl: typing.Optional[float] = None
    win_pnl: typing.Optional[float] = None
    loss_pnl: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    buy_volume: typing.Optional[float] = None
    sell_volume: typing.Optional[float] = None
    winrate: typing.Optional[float] = None
    volume_weighted_winrate: typing.Optional[float] = None
    roi: typing.Optional[float] = None
    volume_weighted_roi: typing.Optional[float] = None
    time_weighted_roi: typing.Optional[float] = None
    pnl_volume_ratio: typing.Optional[float] = None
    token_hit_ratio: typing.Optional[float] = None
    win_loss_size_ratio: typing.Optional[float] = None
    profit_factor: typing.Optional[float] = None
    profit_expectancy: typing.Optional[float] = None
    recovery_factor: typing.Optional[float] = None
    winrate_stability: typing.Optional[float] = None
    winrate_volatility: typing.Optional[float] = None
    pnl_stability: typing.Optional[float] = None
    pnl_volatility: typing.Optional[float] = None
    roi_stability: typing.Optional[float] = None
    roi_volatility: typing.Optional[float] = None
    sharpe_ratio: typing.Optional[float] = None
    sortino_ratio: typing.Optional[float] = None
    max_drawdown: typing.Optional[float] = None
    risk_of_ruin: typing.Optional[float] = None
    turnover: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
