# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_assets_transfer_type_enum import SolanaAssetsTransferTypeEnum


class SolanaAssetsTransferMessage(UniversalBaseModel):
    id: typing.Optional[int] = None
    transfer_type: typing.Optional[SolanaAssetsTransferTypeEnum] = None
    stack_height: typing.Optional[int] = None
    token_address: typing.Optional[str] = None
    from_address: typing.Optional[str] = None
    to_address: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    usd_amount: typing.Optional[float] = None
    block_slot: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None
    tx_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
