# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_wallet_profile_identity import SolanaDexWalletProfileIdentity
from .solana_dex_wallet_profile_label_enum import SolanaDexWalletProfileLabelEnum
from .solana_dex_wallet_profile_metadata import SolanaDexWalletProfileMetadata
from .solana_dex_wallet_profile_metrics import SolanaDexWalletProfileMetrics


class SolanaDexWalletProfileMessage(UniversalBaseModel):
    updated_at: typing.Optional[dt.datetime] = None
    synced_at: typing.Optional[dt.datetime] = None
    wallet_address: typing.Optional[str] = None
    labels: typing.Optional[typing.List[SolanaDexWalletProfileLabelEnum]] = None
    matched_labels: typing.Optional[typing.Dict[str, typing.List[str]]] = None
    dynamic_labels: typing.Optional[typing.List[str]] = None
    metadata: typing.Optional[SolanaDexWalletProfileMetadata] = None
    identity: typing.Optional[SolanaDexWalletProfileIdentity] = None
    metrics: typing.Optional[typing.Dict[str, SolanaDexWalletProfileMetrics]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
