# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_swap_type_enum import SolanaDexSwapTypeEnum
from .solana_dex_trade_direction_enum import SolanaDexTradeDirectionEnum
from .solana_dex_trade_position_state_enum import SolanaDexTradePositionStateEnum


class SolanaDexTrade(UniversalBaseModel):
    id: typing.Optional[int] = None
    protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
    """

    swap_type: typing.Optional[SolanaDexSwapTypeEnum] = None
    wallet_address: typing.Optional[str] = None
    token_address: typing.Optional[str] = None
    quote_address: typing.Optional[str] = None
    position_address: typing.Optional[str] = None
    direction: typing.Optional[SolanaDexTradeDirectionEnum] = None
    position_state: typing.Optional[SolanaDexTradePositionStateEnum] = None
    token_amount: typing.Optional[float] = None
    quote_amount: typing.Optional[float] = None
    native_amount: typing.Optional[float] = None
    usd_amount: typing.Optional[float] = None
    pre_token_balance: typing.Optional[float] = None
    post_token_balance: typing.Optional[float] = None
    token_price: typing.Optional[float] = None
    quote_price: typing.Optional[float] = None
    token_mcap: typing.Optional[float] = None
    block_slot: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None
    tx_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
