# This file was auto-generated by Fern from our API Definition.

import typing

SolanaDexPoolMessageEventTypeEnum = typing.Union[
    typing.Literal["create", "swap", "add_liquidity", "remove_liquidity"], typing.Any
]
