# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_pool_message_event_type_enum import SolanaDexPoolMessageEventTypeEnum
from .solana_dex_pool_message_vault import SolanaDexPoolMessageVault


class SolanaDexPoolMessage(UniversalBaseModel):
    protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
    """

    event_type: typing.Optional[SolanaDexPoolMessageEventTypeEnum] = None
    program_address: typing.Optional[str] = None
    pool_address: typing.Optional[str] = None
    vaults: typing.Optional[typing.List[SolanaDexPoolMessageVault]] = None
    block_slot: typing.Optional[int] = None
    block_time: typing.Optional[dt.datetime] = None
    tx_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
