# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionTopicEnum = typing.Union[
    typing.Literal[
        "solana.dex.price",
        "solana.dex.swap.wallet",
        "solana.dex.swap.token",
        "solana.dex.trade.wallet",
        "solana.dex.trade.token",
        "solana.dex.profile.wallet",
        "solana.dex.profile.token",
        "solana.dex.profile.position",
    ],
    typing.Any,
]
