# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.subscribe_evm_assets_transfers_params import SubscribeEvmAssetsTransfersParams
from ...types.subscribe_evm_dex_pools_params import SubscribeEvmDexPoolsParams
from ...types.subscribe_evm_dex_prices_params import SubscribeEvmDexPricesParams
from ...types.subscribe_evm_dex_swaps_params import SubscribeEvmDexSwapsParams
from ...types.subscribe_evm_dex_token_profiles_params import SubscribeEvmDexTokenProfilesParams
from ...types.subscribe_evm_dex_trades_params import SubscribeEvmDexTradesParams
from ...types.subscribe_evm_dex_wallet_profiles_params import SubscribeEvmDexWalletProfilesParams
from ...types.subscribe_solana_assets_balance_changes_params import SubscribeSolanaAssetsBalanceChangesParams
from ...types.subscribe_solana_assets_transfers_params import SubscribeSolanaAssetsTransfersParams
from ...types.subscribe_solana_dex_pools_params import SubscribeSolanaDexPoolsParams
from ...types.subscribe_solana_dex_position_profiles_params import SubscribeSolanaDexPositionProfilesParams
from ...types.subscribe_solana_dex_prices_params import SubscribeSolanaDexPricesParams
from ...types.subscribe_solana_dex_swaps_params import SubscribeSolanaDexSwapsParams
from ...types.subscribe_solana_dex_token_profiles_params import SubscribeSolanaDexTokenProfilesParams
from ...types.subscribe_solana_dex_trades_params import SubscribeSolanaDexTradesParams
from ...types.subscribe_solana_dex_wallet_profiles_params import SubscribeSolanaDexWalletProfilesParams

SubscribePayloadParams = typing.Union[
    SubscribeSolanaDexPricesParams,
    SubscribeSolanaDexSwapsParams,
    SubscribeSolanaDexTradesParams,
    SubscribeSolanaDexPoolsParams,
    SubscribeSolanaDexWalletProfilesParams,
    SubscribeSolanaDexTokenProfilesParams,
    SubscribeSolanaDexPositionProfilesParams,
    SubscribeSolanaAssetsTransfersParams,
    SubscribeSolanaAssetsBalanceChangesParams,
    SubscribeEvmDexPricesParams,
    SubscribeEvmDexSwapsParams,
    SubscribeEvmDexTradesParams,
    SubscribeEvmDexPoolsParams,
    SubscribeEvmDexWalletProfilesParams,
    SubscribeEvmDexTokenProfilesParams,
    SubscribeEvmAssetsTransfersParams,
]
