# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subscribe_payload_params import SubscribePayloadParams
from .subscription_method_enum import SubscriptionMethodEnum
from .subscription_topic_enum import SubscriptionTopicEnum


class SubscribePayload(UniversalBaseModel):
    method: typing.Optional[SubscriptionMethodEnum] = None
    topic: typing.Optional[SubscriptionTopicEnum] = None
    params: typing.Optional[SubscribePayloadParams] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
