# This file was auto-generated by Fern from our API Definition.

import typing

from .evm_assets_transfer_message import EvmAssetsTransferMessage
from .evm_dex_pool_message import EvmDexPoolMessage
from .evm_dex_price_message import EvmDexPriceMessage
from .evm_dex_swap_message import EvmDexSwapMessage
from .evm_dex_token_profile_message import EvmDexTokenProfileMessage
from .evm_dex_trade_message import EvmDexTradeMessage
from .evm_dex_wallet_profile_message import EvmDexWalletProfileMessage
from .solana_assets_balance_change_message import SolanaAssetsBalanceChangeMessage
from .solana_assets_transfer_message import SolanaAssetsTransferMessage
from .solana_dex_pool_message import SolanaDexPoolMessage
from .solana_dex_position_profile_message import SolanaDexPositionProfileMessage
from .solana_dex_price_message import SolanaDexPriceMessage
from .solana_dex_swap_message import SolanaDexSwapMessage
from .solana_dex_token_profile_message import SolanaDexTokenProfileMessage
from .solana_dex_trade_message import SolanaDexTradeMessage
from .solana_dex_wallet_profile_message import SolanaDexWalletProfileMessage

SubscriptionMessageData = typing.Union[
    SolanaDexPriceMessage,
    SolanaDexSwapMessage,
    SolanaDexTradeMessage,
    SolanaDexPoolMessage,
    SolanaDexWalletProfileMessage,
    SolanaDexTokenProfileMessage,
    SolanaDexPositionProfileMessage,
    SolanaAssetsTransferMessage,
    SolanaAssetsBalanceChangeMessage,
    EvmDexPriceMessage,
    EvmDexSwapMessage,
    EvmDexTradeMessage,
    EvmDexPoolMessage,
    EvmDexWalletProfileMessage,
    EvmDexTokenProfileMessage,
    EvmAssetsTransferMessage,
]
