# This file was auto-generated by Fern from our API Definition.

import typing

from .solana_dex_price import SolanaDexPrice
from .solana_dex_swap import SolanaDexSwap
from .solana_dex_token_profile import SolanaDexTokenProfile
from .solana_dex_trade import SolanaDexTrade
from .solana_dex_wallet_profile import SolanaDexWalletProfile

SubscriptionMessageData = typing.Union[
    SolanaDexPrice, SolanaDexSwap, SolanaDexTrade, SolanaDexWalletProfile, SolanaDexTokenProfile
]
