# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionTopicEnum = typing.Union[
    typing.Literal[
        "solana.dex.prices",
        "solana.dex.swaps",
        "solana.dex.trades",
        "solana.dex.pools",
        "solana.dex.profiles.wallet",
        "solana.dex.profiles.token",
        "solana.dex.profiles.position",
        "solana.assets.transfers",
        "solana.assets.balance-changes",
        "evm.dex.prices",
        "evm.dex.swaps",
        "evm.dex.trades",
        "evm.dex.pools",
        "evm.dex.profiles.wallet",
        "evm.dex.profiles.token",
        "evm.assets.transfers",
    ],
    typing.Any,
]
