# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.subscribe_solana_dex_position_profiles_params import SubscribeSolanaDexPositionProfilesParams
from ...types.subscribe_solana_dex_prices_params import SubscribeSolanaDexPricesParams
from ...types.subscribe_solana_dex_swaps_params import SubscribeSolanaDexSwapsParams
from ...types.subscribe_solana_dex_token_profiles_params import SubscribeSolanaDexTokenProfilesParams
from ...types.subscribe_solana_dex_trades_params import SubscribeSolanaDexTradesParams
from ...types.subscribe_solana_dex_wallet_profiles_params import SubscribeSolanaDexWalletProfilesParams

SubscribePayloadParams = typing.Union[
    SubscribeSolanaDexPricesParams,
    SubscribeSolanaDexSwapsParams,
    SubscribeSolanaDexTradesParams,
    SubscribeSolanaDexWalletProfilesParams,
    SubscribeSolanaDexTokenProfilesParams,
    SubscribeSolanaDexPositionProfilesParams,
]
