# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subscription_message_data import SubscriptionMessageData
from .subscription_topic_enum import SubscriptionTopicEnum


class SubscriptionMessage(UniversalBaseModel):
    topic: typing.Optional[SubscriptionTopicEnum] = None
    data: typing.Optional[SubscriptionMessageData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
