# This file was auto-generated by Fern from our API Definition.

import typing

from .solana_assets_balance_change_message import SolanaAssetsBalanceChangeMessage
from .solana_assets_transfer_message import SolanaAssetsTransferMessage
from .solana_dex_pool_message import SolanaDexPoolMessage
from .solana_dex_price_message import SolanaDexPriceMessage
from .solana_dex_swap_message import SolanaDexSwapMessage
from .solana_dex_token_profile_message import SolanaDexTokenProfileMessage
from .solana_dex_trade_message import SolanaDexTradeMessage
from .solana_dex_wallet_profile_message import SolanaDexWalletProfileMessage

SubscriptionMessageData = typing.Union[
    SolanaDexPriceMessage,
    SolanaDexSwapMessage,
    SolanaDexTradeMessage,
    SolanaDexPoolMessage,
    SolanaDexWalletProfileMessage,
    SolanaDexTokenProfileMessage,
    SolanaAssetsTransferMessage,
    SolanaAssetsBalanceChangeMessage,
]
