# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.unsubscribe_solana_dex_position_profiles_params import UnsubscribeSolanaDexPositionProfilesParams
from ...types.unsubscribe_solana_dex_prices_params import UnsubscribeSolanaDexPricesParams
from ...types.unsubscribe_solana_dex_swaps_params import UnsubscribeSolanaDexSwapsParams
from ...types.unsubscribe_solana_dex_token_profiles_params import UnsubscribeSolanaDexTokenProfilesParams
from ...types.unsubscribe_solana_dex_trades_params import UnsubscribeSolanaDexTradesParams
from ...types.unsubscribe_solana_dex_wallet_profiles_params import UnsubscribeSolanaDexWalletProfilesParams

UnsubscribePayloadParams = typing.Union[
    UnsubscribeSolanaDexPricesParams,
    UnsubscribeSolanaDexSwapsParams,
    UnsubscribeSolanaDexTradesParams,
    UnsubscribeSolanaDexWalletProfilesParams,
    UnsubscribeSolanaDexTokenProfilesParams,
    UnsubscribeSolanaDexPositionProfilesParams,
]
