# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PayloadPagination(UniversalBaseModel):
    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of results to return in a single page.
    """

    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
