# This file was auto-generated by Fern from our API Definition.

import typing

from .solana_dex_token_profile_label_enum import SolanaDexTokenProfileLabelEnum

SolanaDexTokenProfileLabels = typing.List[SolanaDexTokenProfileLabelEnum]
