# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_token_profile_time_window_enum import SolanaDexTokenProfileTimeWindowEnum


class SolanaDexTokenProfilePayloadOptions(UniversalBaseModel):
    """
    Controls which optional sections are included in each returned token profile.
    """

    include_metadata: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, includes the `metadata` object in each returned profile.
    """

    include_market: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, includes the `market` object (price, liquidity, supply) in each returned profile.
    """

    include_labels: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, includes the `labels` array in each returned profile.
    """

    include_metrics: typing.Optional[typing.List[SolanaDexTokenProfileTimeWindowEnum]] = pydantic.Field(default=None)
    """
    Time windows for which metrics should be included. Windows not listed are omitted from the response.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
