# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SolanaDexPriceCandle(UniversalBaseModel):
    timestamp: typing.Optional[dt.datetime] = None
    open: typing.Optional[float] = None
    high: typing.Optional[float] = None
    low: typing.Optional[float] = None
    close: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
