# This file was auto-generated by Fern from our API Definition.

import typing

from .solana_dex_wallet_profile_label_enum import SolanaDexWalletProfileLabelEnum

SolanaDexWalletProfileLabels = typing.List[SolanaDexWalletProfileLabelEnum]
