# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .solana_dex_profile_search_payload_sort_direction_enum import SolanaDexProfileSearchPayloadSortDirectionEnum


class SolanaDexProfileSearchPayloadSort(UniversalBaseModel):
    """
    Rule that determines the order in which matching profiles are returned.
    """

    field: str = pydantic.Field()
    """
    Field path to sort results by.
    """

    direction: SolanaDexProfileSearchPayloadSortDirectionEnum

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
