# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawSolanaClient, RawSolanaClient

if typing.TYPE_CHECKING:
    from .dex.client import AsyncDexClient, DexClient


class SolanaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSolanaClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._dex: typing.Optional[DexClient] = None

    @property
    def with_raw_response(self) -> RawSolanaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSolanaClient
        """
        return self._raw_client

    @property
    def dex(self):
        if self._dex is None:
            from .dex.client import DexClient  # noqa: E402

            self._dex = DexClient(client_wrapper=self._client_wrapper)
        return self._dex


class AsyncSolanaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSolanaClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._dex: typing.Optional[AsyncDexClient] = None

    @property
    def with_raw_response(self) -> AsyncRawSolanaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSolanaClient
        """
        return self._raw_client

    @property
    def dex(self):
        if self._dex is None:
            from .dex.client import AsyncDexClient  # noqa: E402

            self._dex = AsyncDexClient(client_wrapper=self._client_wrapper)
        return self._dex
