# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawApiClient, RawApiClient

if typing.TYPE_CHECKING:
    from .evm.client import AsyncEvmClient, EvmClient
    from .solana.client import AsyncSolanaClient, SolanaClient


class ApiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._evm: typing.Optional[EvmClient] = None
        self._solana: typing.Optional[SolanaClient] = None

    @property
    def with_raw_response(self) -> RawApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiClient
        """
        return self._raw_client

    @property
    def evm(self):
        if self._evm is None:
            from .evm.client import EvmClient  # noqa: E402

            self._evm = EvmClient(client_wrapper=self._client_wrapper)
        return self._evm

    @property
    def solana(self):
        if self._solana is None:
            from .solana.client import SolanaClient  # noqa: E402

            self._solana = SolanaClient(client_wrapper=self._client_wrapper)
        return self._solana


class AsyncApiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._evm: typing.Optional[AsyncEvmClient] = None
        self._solana: typing.Optional[AsyncSolanaClient] = None

    @property
    def with_raw_response(self) -> AsyncRawApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiClient
        """
        return self._raw_client

    @property
    def evm(self):
        if self._evm is None:
            from .evm.client import AsyncEvmClient  # noqa: E402

            self._evm = AsyncEvmClient(client_wrapper=self._client_wrapper)
        return self._evm

    @property
    def solana(self):
        if self._solana is None:
            from .solana.client import AsyncSolanaClient  # noqa: E402

            self._solana = AsyncSolanaClient(client_wrapper=self._client_wrapper)
        return self._solana
