# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.solana_dex_price import SolanaDexPrice
from ...types.solana_dex_price_candle import SolanaDexPriceCandle
from ...types.solana_dex_price_history import SolanaDexPriceHistory
from ...types.solana_dex_price_stats import SolanaDexPriceStats
from ...types.solana_dex_profile_search_payload_dynamic_labels import SolanaDexProfileSearchPayloadDynamicLabels
from ...types.solana_dex_profile_search_payload_filter import SolanaDexProfileSearchPayloadFilter
from ...types.solana_dex_profile_search_payload_sort import SolanaDexProfileSearchPayloadSort
from ...types.solana_dex_token_profile import SolanaDexTokenProfile
from ...types.solana_dex_token_profile_payload_options import SolanaDexTokenProfilePayloadOptions
from ...types.solana_dex_token_profile_search_payload_query_field import SolanaDexTokenProfileSearchPayloadQueryField
from ...types.solana_dex_wallet_profile import SolanaDexWalletProfile
from ...types.solana_dex_wallet_profile_payload_options import SolanaDexWalletProfilePayloadOptions
from ...types.solana_dex_wallet_profile_search_payload_query import SolanaDexWalletProfileSearchPayloadQuery
from .raw_client import AsyncRawDexClient, RawDexClient
from .types.get_swaps_dex_response import GetSwapsDexResponse
from .types.get_trades_dex_response import GetTradesDexResponse
from .types.search_token_profiles_dex_response import SearchTokenProfilesDexResponse
from .types.search_wallet_profiles_dex_response import SearchWalletProfilesDexResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DexClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDexClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDexClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDexClient
        """
        return self._raw_client

    def get_wallet_profile(
        self,
        *,
        wallet: str,
        options: typing.Optional[SolanaDexWalletProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SolanaDexWalletProfile:
        """
        Returns a wallet profile for a specific wallet.

        Parameters
        ----------
        wallet : str
            Wallet address to retrieve the profile for.

        options : typing.Optional[SolanaDexWalletProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SolanaDexWalletProfile
            Wallet profile for the specified wallet.

        Examples
        --------
        from prism import ApiClient, SolanaDexWalletProfilePayloadOptions

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_wallet_profile(
            wallet="suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
            options=SolanaDexWalletProfilePayloadOptions(
                include_metadata=True,
                include_labels=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.get_wallet_profile(wallet=wallet, options=options, request_options=request_options)
        return _response.data

    def search_wallet_profiles(
        self,
        *,
        query: typing.Optional[SolanaDexWalletProfileSearchPayloadQuery] = OMIT,
        filter: typing.Optional[SolanaDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[SolanaDexProfileSearchPayloadSort] = OMIT,
        dynamic_labels: typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels] = OMIT,
        options: typing.Optional[SolanaDexWalletProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchWalletProfilesDexResponse:
        """
        Filter, query, and sort wallet profiles based on specified metrics and conditions.

        Parameters
        ----------
        query : typing.Optional[SolanaDexWalletProfileSearchPayloadQuery]

        filter : typing.Optional[SolanaDexProfileSearchPayloadFilter]

        sort : typing.Optional[SolanaDexProfileSearchPayloadSort]

        dynamic_labels : typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels]

        options : typing.Optional[SolanaDexWalletProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchWalletProfilesDexResponse
            List of wallet profiles found from the search.

        Examples
        --------
        from prism import (
            ApiClient,
            SolanaDexProfileSearchPayloadFilter,
            SolanaDexProfileSearchPayloadSort,
            SolanaDexWalletProfilePayloadOptions,
            SolanaDexWalletProfileSearchPayloadQuery,
        )

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.search_wallet_profiles(
            limit=10,
            query=SolanaDexWalletProfileSearchPayloadQuery(
                text="cupsey",
                fields=["wallet_address"],
            ),
            sort=SolanaDexProfileSearchPayloadSort(
                field="metrics.7d.cumulative_pnl",
                direction="desc",
            ),
            dynamic_labels={"smart": SolanaDexProfileSearchPayloadFilter()},
            options=SolanaDexWalletProfilePayloadOptions(
                include_metadata=True,
                include_labels=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.search_wallet_profiles(
            query=query,
            filter=filter,
            sort=sort,
            dynamic_labels=dynamic_labels,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def get_token_profile(
        self,
        *,
        token: str,
        options: typing.Optional[SolanaDexTokenProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SolanaDexTokenProfile:
        """
        Returns the profile for a specific token.

        Parameters
        ----------
        token : str
            Token address to retrieve the profile for.

        options : typing.Optional[SolanaDexTokenProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SolanaDexTokenProfile
            Profile for the specified token.

        Examples
        --------
        from prism import ApiClient, SolanaDexTokenProfilePayloadOptions

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_token_profile(
            token="Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
            options=SolanaDexTokenProfilePayloadOptions(
                include_metadata=True,
                include_market=True,
                include_labels=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.get_token_profile(token=token, options=options, request_options=request_options)
        return _response.data

    def search_token_profiles(
        self,
        *,
        query: typing.Optional[SolanaDexTokenProfileSearchPayloadQueryField] = OMIT,
        filter: typing.Optional[SolanaDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[SolanaDexProfileSearchPayloadSort] = OMIT,
        dynamic_labels: typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels] = OMIT,
        options: typing.Optional[SolanaDexTokenProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchTokenProfilesDexResponse:
        """
        Filter, query, and sort token profiles based on specified metrics and conditions.

        Parameters
        ----------
        query : typing.Optional[SolanaDexTokenProfileSearchPayloadQueryField]

        filter : typing.Optional[SolanaDexProfileSearchPayloadFilter]

        sort : typing.Optional[SolanaDexProfileSearchPayloadSort]

        dynamic_labels : typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels]

        options : typing.Optional[SolanaDexTokenProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchTokenProfilesDexResponse
            List of filtered and sorted token profiles.

        Examples
        --------
        from prism import (
            ApiClient,
            SolanaDexProfileSearchPayloadFilter,
            SolanaDexProfileSearchPayloadSort,
            SolanaDexTokenProfilePayloadOptions,
            SolanaDexTokenProfileSearchPayloadQueryField,
        )

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.search_token_profiles(
            limit=10,
            query=SolanaDexTokenProfileSearchPayloadQueryField(
                text="bonk",
                fields=["metadata.name"],
            ),
            sort=SolanaDexProfileSearchPayloadSort(
                field="market.liquidity",
                direction="desc",
            ),
            dynamic_labels={"trending": SolanaDexProfileSearchPayloadFilter()},
            options=SolanaDexTokenProfilePayloadOptions(
                include_metadata=True,
                include_market=True,
                include_labels=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.search_token_profiles(
            query=query,
            filter=filter,
            sort=sort,
            dynamic_labels=dynamic_labels,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def get_trades(
        self,
        *,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetTradesDexResponse:
        """
        Returns trades for a wallet, token or both.

        Parameters
        ----------
        wallet : typing.Optional[str]
            Wallet address to filter trades by. When combined with `token`, returns only trades for that wallet on that token.

        token : typing.Optional[str]
            Token address to filter trades by. When combined with `wallet`, returns only trades for that wallet on that token.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTradesDexResponse
            List of trades.

        Examples
        --------
        from prism import ApiClient

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_trades(
            limit=20,
            wallet="suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
        )
        """
        _response = self._raw_client.get_trades(
            wallet=wallet, token=token, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def get_swaps(
        self,
        *,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSwapsDexResponse:
        """
        Returns swaps for a wallet, token or both.

        Parameters
        ----------
        wallet : typing.Optional[str]
            Wallet address to filter swaps by. When combined with `token`, returns only swaps for that wallet on that token.

        token : typing.Optional[str]
            Token address to filter swaps by. When combined with `wallet`, returns only swaps for that wallet on that token.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSwapsDexResponse
            List of swaps.

        Examples
        --------
        from prism import ApiClient

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_swaps(
            limit=20,
            wallet="suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
        )
        """
        _response = self._raw_client.get_swaps(
            wallet=wallet, token=token, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def get_price(
        self, *, tokens: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SolanaDexPrice]:
        """
        Returns prices for one or more tokens.

        Parameters
        ----------
        tokens : typing.Sequence[str]
            Token addresses to retrieve the latest prices for. Accepts between 1 and 1000 tokens per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPrice]
            List of token prices for the specified tokens.

        Examples
        --------
        from prism import ApiClient

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_price(
            tokens=["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
        )
        """
        _response = self._raw_client.get_price(tokens=tokens, request_options=request_options)
        return _response.data

    def get_price_stats(
        self, *, tokens: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SolanaDexPriceStats]:
        """
        Returns price stats for one or more tokens.

        Parameters
        ----------
        tokens : typing.Sequence[str]
            Token addresses to retrieve price statistics for. Accepts between 1 and 1000 tokens per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPriceStats]
            List of price stats for the specified tokens.

        Examples
        --------
        from prism import ApiClient

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_price_stats(
            tokens=["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
        )
        """
        _response = self._raw_client.get_price_stats(tokens=tokens, request_options=request_options)
        return _response.data

    def get_price_candles(
        self,
        *,
        token: str,
        interval: int,
        from_: typing.Optional[dt.datetime] = OMIT,
        to: typing.Optional[dt.datetime] = OMIT,
        count: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SolanaDexPriceCandle]:
        """
        Returns price candles for a specific token.

        Parameters
        ----------
        token : str
            Token address to retrieve price candles for.

        interval : int
            Sampling interval between data points, in seconds.

        from_ : typing.Optional[dt.datetime]
            Start of the candle range, as a date-time RFC3339 string.
            Must be combined with `to` to define a bounded range.

        to : typing.Optional[dt.datetime]
            End of the candle range, as a date-time RFC3339 string. Defaults to the current time.
            Must be combined with either `from` (to define a bounded range) or `count` (to return the N most recent candles ending at `to`).

        count : typing.Optional[int]
            Number of candles to return, ending at `to`.
            Must be combined with `to`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPriceCandle]
            Price candles for the specified token.

        Examples
        --------
        import datetime

        from prism import ApiClient

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_price_candles(
            token="Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
            from_=datetime.datetime.fromisoformat(
                "2026-04-27 00:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2026-04-27 01:00:00+00:00",
            ),
            interval=60,
        )
        """
        _response = self._raw_client.get_price_candles(
            token=token, interval=interval, from_=from_, to=to, count=count, request_options=request_options
        )
        return _response.data

    def get_price_history(
        self,
        *,
        tokens: typing.Sequence[str],
        from_: dt.datetime,
        interval: int,
        to: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SolanaDexPriceHistory]:
        """
        Returns price history for one or more tokens.

        Parameters
        ----------
        tokens : typing.Sequence[str]
            Token addresses to retrieve price history for. Accepts between 1 and 100 tokens per request.

        from_ : dt.datetime
            Start of the history range, as a date-time RFC3339 string.

        interval : int
            Sampling interval between data points, in seconds.

        to : typing.Optional[dt.datetime]
            End of the history range, as a date-time RFC3339 string. Defaults to the current time.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPriceHistory]
            Price history for the specified tokens.

        Examples
        --------
        import datetime

        from prism import ApiClient

        client = ApiClient(
            api_key="YOUR_API_KEY",
        )
        client.solana.dex.get_price_history(
            tokens=["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
            from_=datetime.datetime.fromisoformat(
                "2026-04-27 00:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2026-04-27 01:00:00+00:00",
            ),
            interval=3600,
        )
        """
        _response = self._raw_client.get_price_history(
            tokens=tokens, from_=from_, interval=interval, to=to, request_options=request_options
        )
        return _response.data


class AsyncDexClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDexClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDexClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDexClient
        """
        return self._raw_client

    async def get_wallet_profile(
        self,
        *,
        wallet: str,
        options: typing.Optional[SolanaDexWalletProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SolanaDexWalletProfile:
        """
        Returns a wallet profile for a specific wallet.

        Parameters
        ----------
        wallet : str
            Wallet address to retrieve the profile for.

        options : typing.Optional[SolanaDexWalletProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SolanaDexWalletProfile
            Wallet profile for the specified wallet.

        Examples
        --------
        import asyncio

        from prism import AsyncApiClient, SolanaDexWalletProfilePayloadOptions

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_wallet_profile(
                wallet="suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
                options=SolanaDexWalletProfilePayloadOptions(
                    include_metadata=True,
                    include_labels=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_wallet_profile(
            wallet=wallet, options=options, request_options=request_options
        )
        return _response.data

    async def search_wallet_profiles(
        self,
        *,
        query: typing.Optional[SolanaDexWalletProfileSearchPayloadQuery] = OMIT,
        filter: typing.Optional[SolanaDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[SolanaDexProfileSearchPayloadSort] = OMIT,
        dynamic_labels: typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels] = OMIT,
        options: typing.Optional[SolanaDexWalletProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchWalletProfilesDexResponse:
        """
        Filter, query, and sort wallet profiles based on specified metrics and conditions.

        Parameters
        ----------
        query : typing.Optional[SolanaDexWalletProfileSearchPayloadQuery]

        filter : typing.Optional[SolanaDexProfileSearchPayloadFilter]

        sort : typing.Optional[SolanaDexProfileSearchPayloadSort]

        dynamic_labels : typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels]

        options : typing.Optional[SolanaDexWalletProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchWalletProfilesDexResponse
            List of wallet profiles found from the search.

        Examples
        --------
        import asyncio

        from prism import (
            AsyncApiClient,
            SolanaDexProfileSearchPayloadFilter,
            SolanaDexProfileSearchPayloadSort,
            SolanaDexWalletProfilePayloadOptions,
            SolanaDexWalletProfileSearchPayloadQuery,
        )

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.search_wallet_profiles(
                limit=10,
                query=SolanaDexWalletProfileSearchPayloadQuery(
                    text="cupsey",
                    fields=["wallet_address"],
                ),
                sort=SolanaDexProfileSearchPayloadSort(
                    field="metrics.7d.cumulative_pnl",
                    direction="desc",
                ),
                dynamic_labels={"smart": SolanaDexProfileSearchPayloadFilter()},
                options=SolanaDexWalletProfilePayloadOptions(
                    include_metadata=True,
                    include_labels=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_wallet_profiles(
            query=query,
            filter=filter,
            sort=sort,
            dynamic_labels=dynamic_labels,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_token_profile(
        self,
        *,
        token: str,
        options: typing.Optional[SolanaDexTokenProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SolanaDexTokenProfile:
        """
        Returns the profile for a specific token.

        Parameters
        ----------
        token : str
            Token address to retrieve the profile for.

        options : typing.Optional[SolanaDexTokenProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SolanaDexTokenProfile
            Profile for the specified token.

        Examples
        --------
        import asyncio

        from prism import AsyncApiClient, SolanaDexTokenProfilePayloadOptions

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_token_profile(
                token="Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
                options=SolanaDexTokenProfilePayloadOptions(
                    include_metadata=True,
                    include_market=True,
                    include_labels=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_token_profile(
            token=token, options=options, request_options=request_options
        )
        return _response.data

    async def search_token_profiles(
        self,
        *,
        query: typing.Optional[SolanaDexTokenProfileSearchPayloadQueryField] = OMIT,
        filter: typing.Optional[SolanaDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[SolanaDexProfileSearchPayloadSort] = OMIT,
        dynamic_labels: typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels] = OMIT,
        options: typing.Optional[SolanaDexTokenProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchTokenProfilesDexResponse:
        """
        Filter, query, and sort token profiles based on specified metrics and conditions.

        Parameters
        ----------
        query : typing.Optional[SolanaDexTokenProfileSearchPayloadQueryField]

        filter : typing.Optional[SolanaDexProfileSearchPayloadFilter]

        sort : typing.Optional[SolanaDexProfileSearchPayloadSort]

        dynamic_labels : typing.Optional[SolanaDexProfileSearchPayloadDynamicLabels]

        options : typing.Optional[SolanaDexTokenProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchTokenProfilesDexResponse
            List of filtered and sorted token profiles.

        Examples
        --------
        import asyncio

        from prism import (
            AsyncApiClient,
            SolanaDexProfileSearchPayloadFilter,
            SolanaDexProfileSearchPayloadSort,
            SolanaDexTokenProfilePayloadOptions,
            SolanaDexTokenProfileSearchPayloadQueryField,
        )

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.search_token_profiles(
                limit=10,
                query=SolanaDexTokenProfileSearchPayloadQueryField(
                    text="bonk",
                    fields=["metadata.name"],
                ),
                sort=SolanaDexProfileSearchPayloadSort(
                    field="market.liquidity",
                    direction="desc",
                ),
                dynamic_labels={"trending": SolanaDexProfileSearchPayloadFilter()},
                options=SolanaDexTokenProfilePayloadOptions(
                    include_metadata=True,
                    include_market=True,
                    include_labels=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_token_profiles(
            query=query,
            filter=filter,
            sort=sort,
            dynamic_labels=dynamic_labels,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_trades(
        self,
        *,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetTradesDexResponse:
        """
        Returns trades for a wallet, token or both.

        Parameters
        ----------
        wallet : typing.Optional[str]
            Wallet address to filter trades by. When combined with `token`, returns only trades for that wallet on that token.

        token : typing.Optional[str]
            Token address to filter trades by. When combined with `wallet`, returns only trades for that wallet on that token.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTradesDexResponse
            List of trades.

        Examples
        --------
        import asyncio

        from prism import AsyncApiClient

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_trades(
                limit=20,
                wallet="suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_trades(
            wallet=wallet, token=token, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def get_swaps(
        self,
        *,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSwapsDexResponse:
        """
        Returns swaps for a wallet, token or both.

        Parameters
        ----------
        wallet : typing.Optional[str]
            Wallet address to filter swaps by. When combined with `token`, returns only swaps for that wallet on that token.

        token : typing.Optional[str]
            Token address to filter swaps by. When combined with `wallet`, returns only swaps for that wallet on that token.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSwapsDexResponse
            List of swaps.

        Examples
        --------
        import asyncio

        from prism import AsyncApiClient

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_swaps(
                limit=20,
                wallet="suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_swaps(
            wallet=wallet, token=token, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def get_price(
        self, *, tokens: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SolanaDexPrice]:
        """
        Returns prices for one or more tokens.

        Parameters
        ----------
        tokens : typing.Sequence[str]
            Token addresses to retrieve the latest prices for. Accepts between 1 and 1000 tokens per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPrice]
            List of token prices for the specified tokens.

        Examples
        --------
        import asyncio

        from prism import AsyncApiClient

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_price(
                tokens=["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price(tokens=tokens, request_options=request_options)
        return _response.data

    async def get_price_stats(
        self, *, tokens: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SolanaDexPriceStats]:
        """
        Returns price stats for one or more tokens.

        Parameters
        ----------
        tokens : typing.Sequence[str]
            Token addresses to retrieve price statistics for. Accepts between 1 and 1000 tokens per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPriceStats]
            List of price stats for the specified tokens.

        Examples
        --------
        import asyncio

        from prism import AsyncApiClient

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_price_stats(
                tokens=["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price_stats(tokens=tokens, request_options=request_options)
        return _response.data

    async def get_price_candles(
        self,
        *,
        token: str,
        interval: int,
        from_: typing.Optional[dt.datetime] = OMIT,
        to: typing.Optional[dt.datetime] = OMIT,
        count: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SolanaDexPriceCandle]:
        """
        Returns price candles for a specific token.

        Parameters
        ----------
        token : str
            Token address to retrieve price candles for.

        interval : int
            Sampling interval between data points, in seconds.

        from_ : typing.Optional[dt.datetime]
            Start of the candle range, as a date-time RFC3339 string.
            Must be combined with `to` to define a bounded range.

        to : typing.Optional[dt.datetime]
            End of the candle range, as a date-time RFC3339 string. Defaults to the current time.
            Must be combined with either `from` (to define a bounded range) or `count` (to return the N most recent candles ending at `to`).

        count : typing.Optional[int]
            Number of candles to return, ending at `to`.
            Must be combined with `to`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPriceCandle]
            Price candles for the specified token.

        Examples
        --------
        import asyncio
        import datetime

        from prism import AsyncApiClient

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_price_candles(
                token="Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
                from_=datetime.datetime.fromisoformat(
                    "2026-04-27 00:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2026-04-27 01:00:00+00:00",
                ),
                interval=60,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price_candles(
            token=token, interval=interval, from_=from_, to=to, count=count, request_options=request_options
        )
        return _response.data

    async def get_price_history(
        self,
        *,
        tokens: typing.Sequence[str],
        from_: dt.datetime,
        interval: int,
        to: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SolanaDexPriceHistory]:
        """
        Returns price history for one or more tokens.

        Parameters
        ----------
        tokens : typing.Sequence[str]
            Token addresses to retrieve price history for. Accepts between 1 and 100 tokens per request.

        from_ : dt.datetime
            Start of the history range, as a date-time RFC3339 string.

        interval : int
            Sampling interval between data points, in seconds.

        to : typing.Optional[dt.datetime]
            End of the history range, as a date-time RFC3339 string. Defaults to the current time.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SolanaDexPriceHistory]
            Price history for the specified tokens.

        Examples
        --------
        import asyncio
        import datetime

        from prism import AsyncApiClient

        client = AsyncApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.solana.dex.get_price_history(
                tokens=["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
                from_=datetime.datetime.fromisoformat(
                    "2026-04-27 00:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2026-04-27 01:00:00+00:00",
                ),
                interval=3600,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price_history(
            tokens=tokens, from_=from_, interval=interval, to=to, request_options=request_options
        )
        return _response.data
