# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .position_profiles_subscription_message import PositionProfilesSubscriptionMessage
    from .subscribe_position_profiles import SubscribePositionProfiles
    from .subscribe_position_profiles_params import SubscribePositionProfilesParams
    from .subscribe_token_profiles import SubscribeTokenProfiles
    from .subscribe_token_profiles_params import SubscribeTokenProfilesParams
    from .subscribe_wallet_profiles import SubscribeWalletProfiles
    from .subscribe_wallet_profiles_params import SubscribeWalletProfilesParams
    from .token_profiles_subscription_message import TokenProfilesSubscriptionMessage
    from .unsubscribe_position_profiles import UnsubscribePositionProfiles
    from .unsubscribe_position_profiles_params import UnsubscribePositionProfilesParams
    from .unsubscribe_token_profiles import UnsubscribeTokenProfiles
    from .unsubscribe_token_profiles_params import UnsubscribeTokenProfilesParams
    from .unsubscribe_wallet_profiles import UnsubscribeWalletProfiles
    from .unsubscribe_wallet_profiles_params import UnsubscribeWalletProfilesParams
    from .wallet_profiles_subscription_message import WalletProfilesSubscriptionMessage
_dynamic_imports: typing.Dict[str, str] = {
    "PositionProfilesSubscriptionMessage": ".position_profiles_subscription_message",
    "SubscribePositionProfiles": ".subscribe_position_profiles",
    "SubscribePositionProfilesParams": ".subscribe_position_profiles_params",
    "SubscribeTokenProfiles": ".subscribe_token_profiles",
    "SubscribeTokenProfilesParams": ".subscribe_token_profiles_params",
    "SubscribeWalletProfiles": ".subscribe_wallet_profiles",
    "SubscribeWalletProfilesParams": ".subscribe_wallet_profiles_params",
    "TokenProfilesSubscriptionMessage": ".token_profiles_subscription_message",
    "UnsubscribePositionProfiles": ".unsubscribe_position_profiles",
    "UnsubscribePositionProfilesParams": ".unsubscribe_position_profiles_params",
    "UnsubscribeTokenProfiles": ".unsubscribe_token_profiles",
    "UnsubscribeTokenProfilesParams": ".unsubscribe_token_profiles_params",
    "UnsubscribeWalletProfiles": ".unsubscribe_wallet_profiles",
    "UnsubscribeWalletProfilesParams": ".unsubscribe_wallet_profiles_params",
    "WalletProfilesSubscriptionMessage": ".wallet_profiles_subscription_message",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PositionProfilesSubscriptionMessage",
    "SubscribePositionProfiles",
    "SubscribePositionProfilesParams",
    "SubscribeTokenProfiles",
    "SubscribeTokenProfilesParams",
    "SubscribeWalletProfiles",
    "SubscribeWalletProfilesParams",
    "TokenProfilesSubscriptionMessage",
    "UnsubscribePositionProfiles",
    "UnsubscribePositionProfilesParams",
    "UnsubscribeTokenProfiles",
    "UnsubscribeTokenProfilesParams",
    "UnsubscribeWalletProfiles",
    "UnsubscribeWalletProfilesParams",
    "WalletProfilesSubscriptionMessage",
]
