# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        SubscribeSolanaAssetsBalanceChangesParams,
        SubscribeSolanaAssetsTransfersParams,
        SubscribeSolanaDexPoolsParams,
        SubscribeSolanaDexPositionProfilesParams,
        SubscribeSolanaDexPricesParams,
        SubscribeSolanaDexSwapsParams,
        SubscribeSolanaDexTokenProfilesParams,
        SubscribeSolanaDexTradesParams,
        SubscribeSolanaDexWalletProfilesParams,
    )
    from . import subscription
    from .subscription import (
        SolanaAssetsBalanceChangeMessage,
        SolanaAssetsBalanceChangeTypeEnum,
        SolanaAssetsTransferMessage,
        SolanaAssetsTransferTypeEnum,
        SolanaDexPoolMessage,
        SolanaDexPoolMessageEventTypeEnum,
        SolanaDexPoolMessageVault,
        SolanaDexPriceMessage,
        SolanaDexSwapMessage,
        SolanaDexSwapTypeEnum,
        SolanaDexTokenProfileLabelEnum,
        SolanaDexTokenProfileMarket,
        SolanaDexTokenProfileMessage,
        SolanaDexTokenProfileMetadata,
        SolanaDexTokenProfileMetrics,
        SolanaDexTradeDirectionEnum,
        SolanaDexTradeMessage,
        SolanaDexTradePositionStateEnum,
        SolanaDexWalletProfileIdentity,
        SolanaDexWalletProfileLabelEnum,
        SolanaDexWalletProfileMessage,
        SolanaDexWalletProfileMetadata,
        SolanaDexWalletProfileMetrics,
        SubscribePayload,
        SubscribePayloadParams,
        SubscriptionMessage,
        SubscriptionMessageData,
        SubscriptionMethodEnum,
        SubscriptionTopicEnum,
        UnsubscribePayload,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "SolanaAssetsBalanceChangeMessage": ".subscription",
    "SolanaAssetsBalanceChangeTypeEnum": ".subscription",
    "SolanaAssetsTransferMessage": ".subscription",
    "SolanaAssetsTransferTypeEnum": ".subscription",
    "SolanaDexPoolMessage": ".subscription",
    "SolanaDexPoolMessageEventTypeEnum": ".subscription",
    "SolanaDexPoolMessageVault": ".subscription",
    "SolanaDexPriceMessage": ".subscription",
    "SolanaDexSwapMessage": ".subscription",
    "SolanaDexSwapTypeEnum": ".subscription",
    "SolanaDexTokenProfileLabelEnum": ".subscription",
    "SolanaDexTokenProfileMarket": ".subscription",
    "SolanaDexTokenProfileMessage": ".subscription",
    "SolanaDexTokenProfileMetadata": ".subscription",
    "SolanaDexTokenProfileMetrics": ".subscription",
    "SolanaDexTradeDirectionEnum": ".subscription",
    "SolanaDexTradeMessage": ".subscription",
    "SolanaDexTradePositionStateEnum": ".subscription",
    "SolanaDexWalletProfileIdentity": ".subscription",
    "SolanaDexWalletProfileLabelEnum": ".subscription",
    "SolanaDexWalletProfileMessage": ".subscription",
    "SolanaDexWalletProfileMetadata": ".subscription",
    "SolanaDexWalletProfileMetrics": ".subscription",
    "SubscribePayload": ".subscription",
    "SubscribePayloadParams": ".subscription",
    "SubscribeSolanaAssetsBalanceChangesParams": ".types",
    "SubscribeSolanaAssetsTransfersParams": ".types",
    "SubscribeSolanaDexPoolsParams": ".types",
    "SubscribeSolanaDexPositionProfilesParams": ".types",
    "SubscribeSolanaDexPricesParams": ".types",
    "SubscribeSolanaDexSwapsParams": ".types",
    "SubscribeSolanaDexTokenProfilesParams": ".types",
    "SubscribeSolanaDexTradesParams": ".types",
    "SubscribeSolanaDexWalletProfilesParams": ".types",
    "SubscriptionMessage": ".subscription",
    "SubscriptionMessageData": ".subscription",
    "SubscriptionMethodEnum": ".subscription",
    "SubscriptionTopicEnum": ".subscription",
    "UnsubscribePayload": ".subscription",
    "subscription": ".subscription",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SolanaAssetsBalanceChangeMessage",
    "SolanaAssetsBalanceChangeTypeEnum",
    "SolanaAssetsTransferMessage",
    "SolanaAssetsTransferTypeEnum",
    "SolanaDexPoolMessage",
    "SolanaDexPoolMessageEventTypeEnum",
    "SolanaDexPoolMessageVault",
    "SolanaDexPriceMessage",
    "SolanaDexSwapMessage",
    "SolanaDexSwapTypeEnum",
    "SolanaDexTokenProfileLabelEnum",
    "SolanaDexTokenProfileMarket",
    "SolanaDexTokenProfileMessage",
    "SolanaDexTokenProfileMetadata",
    "SolanaDexTokenProfileMetrics",
    "SolanaDexTradeDirectionEnum",
    "SolanaDexTradeMessage",
    "SolanaDexTradePositionStateEnum",
    "SolanaDexWalletProfileIdentity",
    "SolanaDexWalletProfileLabelEnum",
    "SolanaDexWalletProfileMessage",
    "SolanaDexWalletProfileMetadata",
    "SolanaDexWalletProfileMetrics",
    "SubscribePayload",
    "SubscribePayloadParams",
    "SubscribeSolanaAssetsBalanceChangesParams",
    "SubscribeSolanaAssetsTransfersParams",
    "SubscribeSolanaDexPoolsParams",
    "SubscribeSolanaDexPositionProfilesParams",
    "SubscribeSolanaDexPricesParams",
    "SubscribeSolanaDexSwapsParams",
    "SubscribeSolanaDexTokenProfilesParams",
    "SubscribeSolanaDexTradesParams",
    "SubscribeSolanaDexWalletProfilesParams",
    "SubscriptionMessage",
    "SubscriptionMessageData",
    "SubscriptionMethodEnum",
    "SubscriptionTopicEnum",
    "UnsubscribePayload",
    "subscription",
]
