# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BadRequestErrorBody,
        ForbiddenErrorBody,
        InternalServerErrorBody,
        PaginatedResponse,
        PayloadPagination,
        SolanaDexPrice,
        SolanaDexPriceCandle,
        SolanaDexPriceHistory,
        SolanaDexPriceSnapshot,
        SolanaDexPriceStats,
        SolanaDexProfileDynamicLabels,
        SolanaDexProfileSearchPayloadDynamicLabels,
        SolanaDexProfileSearchPayloadFilter,
        SolanaDexProfileSearchPayloadFilterOperators,
        SolanaDexProfileSearchPayloadFilterOperatorsEq,
        SolanaDexProfileSearchPayloadFilterOperatorsInItem,
        SolanaDexProfileSearchPayloadFilterOperatorsNe,
        SolanaDexProfileSearchPayloadFilterOperatorsNinItem,
        SolanaDexProfileSearchPayloadQuery,
        SolanaDexProfileSearchPayloadSort,
        SolanaDexProfileSearchPayloadSortDirectionEnum,
        SolanaDexProtocolField,
        SolanaDexSwap,
        SolanaDexSwapTypeEnum,
        SolanaDexTokenProfile,
        SolanaDexTokenProfileLabelEnum,
        SolanaDexTokenProfileLabels,
        SolanaDexTokenProfileMarket,
        SolanaDexTokenProfileMetadata,
        SolanaDexTokenProfileMetrics,
        SolanaDexTokenProfilePayloadOptions,
        SolanaDexTokenProfileSearchPayloadQueryField,
        SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum,
        SolanaDexTokenProfileTimeWindowEnum,
        SolanaDexTrade,
        SolanaDexTradeDirectionEnum,
        SolanaDexTradePositionStateEnum,
        SolanaDexWalletProfile,
        SolanaDexWalletProfileIdentity,
        SolanaDexWalletProfileLabelEnum,
        SolanaDexWalletProfileLabels,
        SolanaDexWalletProfileMetadata,
        SolanaDexWalletProfileMetrics,
        SolanaDexWalletProfilePayloadOptions,
        SolanaDexWalletProfileSearchPayloadQuery,
        SolanaDexWalletProfileSearchPayloadQueryTargetsEnum,
        SolanaDexWalletProfileTimeWindowEnum,
        TooManyRequestsErrorBody,
        UnauthorizedErrorBody,
    )
    from .errors import BadRequestError, ForbiddenError, InternalServerError, TooManyRequestsError, UnauthorizedError
    from . import solana
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import ApiClient, AsyncApiClient
    from .environment import ApiClientEnvironment
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "ApiClient": ".client",
    "ApiClientEnvironment": ".environment",
    "AsyncApiClient": ".client",
    "BadRequestError": ".errors",
    "BadRequestErrorBody": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ForbiddenError": ".errors",
    "ForbiddenErrorBody": ".types",
    "InternalServerError": ".errors",
    "InternalServerErrorBody": ".types",
    "PaginatedResponse": ".types",
    "PayloadPagination": ".types",
    "SolanaDexPrice": ".types",
    "SolanaDexPriceCandle": ".types",
    "SolanaDexPriceHistory": ".types",
    "SolanaDexPriceSnapshot": ".types",
    "SolanaDexPriceStats": ".types",
    "SolanaDexProfileDynamicLabels": ".types",
    "SolanaDexProfileSearchPayloadDynamicLabels": ".types",
    "SolanaDexProfileSearchPayloadFilter": ".types",
    "SolanaDexProfileSearchPayloadFilterOperators": ".types",
    "SolanaDexProfileSearchPayloadFilterOperatorsEq": ".types",
    "SolanaDexProfileSearchPayloadFilterOperatorsInItem": ".types",
    "SolanaDexProfileSearchPayloadFilterOperatorsNe": ".types",
    "SolanaDexProfileSearchPayloadFilterOperatorsNinItem": ".types",
    "SolanaDexProfileSearchPayloadQuery": ".types",
    "SolanaDexProfileSearchPayloadSort": ".types",
    "SolanaDexProfileSearchPayloadSortDirectionEnum": ".types",
    "SolanaDexProtocolField": ".types",
    "SolanaDexSwap": ".types",
    "SolanaDexSwapTypeEnum": ".types",
    "SolanaDexTokenProfile": ".types",
    "SolanaDexTokenProfileLabelEnum": ".types",
    "SolanaDexTokenProfileLabels": ".types",
    "SolanaDexTokenProfileMarket": ".types",
    "SolanaDexTokenProfileMetadata": ".types",
    "SolanaDexTokenProfileMetrics": ".types",
    "SolanaDexTokenProfilePayloadOptions": ".types",
    "SolanaDexTokenProfileSearchPayloadQueryField": ".types",
    "SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum": ".types",
    "SolanaDexTokenProfileTimeWindowEnum": ".types",
    "SolanaDexTrade": ".types",
    "SolanaDexTradeDirectionEnum": ".types",
    "SolanaDexTradePositionStateEnum": ".types",
    "SolanaDexWalletProfile": ".types",
    "SolanaDexWalletProfileIdentity": ".types",
    "SolanaDexWalletProfileLabelEnum": ".types",
    "SolanaDexWalletProfileLabels": ".types",
    "SolanaDexWalletProfileMetadata": ".types",
    "SolanaDexWalletProfileMetrics": ".types",
    "SolanaDexWalletProfilePayloadOptions": ".types",
    "SolanaDexWalletProfileSearchPayloadQuery": ".types",
    "SolanaDexWalletProfileSearchPayloadQueryTargetsEnum": ".types",
    "SolanaDexWalletProfileTimeWindowEnum": ".types",
    "TooManyRequestsError": ".errors",
    "TooManyRequestsErrorBody": ".types",
    "UnauthorizedError": ".errors",
    "UnauthorizedErrorBody": ".types",
    "__version__": ".version",
    "solana": ".solana",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiClient",
    "ApiClientEnvironment",
    "AsyncApiClient",
    "BadRequestError",
    "BadRequestErrorBody",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ForbiddenError",
    "ForbiddenErrorBody",
    "InternalServerError",
    "InternalServerErrorBody",
    "PaginatedResponse",
    "PayloadPagination",
    "SolanaDexPrice",
    "SolanaDexPriceCandle",
    "SolanaDexPriceHistory",
    "SolanaDexPriceSnapshot",
    "SolanaDexPriceStats",
    "SolanaDexProfileDynamicLabels",
    "SolanaDexProfileSearchPayloadDynamicLabels",
    "SolanaDexProfileSearchPayloadFilter",
    "SolanaDexProfileSearchPayloadFilterOperators",
    "SolanaDexProfileSearchPayloadFilterOperatorsEq",
    "SolanaDexProfileSearchPayloadFilterOperatorsInItem",
    "SolanaDexProfileSearchPayloadFilterOperatorsNe",
    "SolanaDexProfileSearchPayloadFilterOperatorsNinItem",
    "SolanaDexProfileSearchPayloadQuery",
    "SolanaDexProfileSearchPayloadSort",
    "SolanaDexProfileSearchPayloadSortDirectionEnum",
    "SolanaDexProtocolField",
    "SolanaDexSwap",
    "SolanaDexSwapTypeEnum",
    "SolanaDexTokenProfile",
    "SolanaDexTokenProfileLabelEnum",
    "SolanaDexTokenProfileLabels",
    "SolanaDexTokenProfileMarket",
    "SolanaDexTokenProfileMetadata",
    "SolanaDexTokenProfileMetrics",
    "SolanaDexTokenProfilePayloadOptions",
    "SolanaDexTokenProfileSearchPayloadQueryField",
    "SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum",
    "SolanaDexTokenProfileTimeWindowEnum",
    "SolanaDexTrade",
    "SolanaDexTradeDirectionEnum",
    "SolanaDexTradePositionStateEnum",
    "SolanaDexWalletProfile",
    "SolanaDexWalletProfileIdentity",
    "SolanaDexWalletProfileLabelEnum",
    "SolanaDexWalletProfileLabels",
    "SolanaDexWalletProfileMetadata",
    "SolanaDexWalletProfileMetrics",
    "SolanaDexWalletProfilePayloadOptions",
    "SolanaDexWalletProfileSearchPayloadQuery",
    "SolanaDexWalletProfileSearchPayloadQueryTargetsEnum",
    "SolanaDexWalletProfileTimeWindowEnum",
    "TooManyRequestsError",
    "TooManyRequestsErrorBody",
    "UnauthorizedError",
    "UnauthorizedErrorBody",
    "__version__",
    "solana",
]
