# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .subscribe_solana_dex_position_profiles_params import SubscribeSolanaDexPositionProfilesParams
    from .subscribe_solana_dex_prices_params import SubscribeSolanaDexPricesParams
    from .subscribe_solana_dex_swaps_params import SubscribeSolanaDexSwapsParams
    from .subscribe_solana_dex_token_profiles_params import SubscribeSolanaDexTokenProfilesParams
    from .subscribe_solana_dex_trades_params import SubscribeSolanaDexTradesParams
    from .subscribe_solana_dex_wallet_profiles_params import SubscribeSolanaDexWalletProfilesParams
    from .unsubscribe_solana_dex_position_profiles_params import UnsubscribeSolanaDexPositionProfilesParams
    from .unsubscribe_solana_dex_prices_params import UnsubscribeSolanaDexPricesParams
    from .unsubscribe_solana_dex_swaps_params import UnsubscribeSolanaDexSwapsParams
    from .unsubscribe_solana_dex_token_profiles_params import UnsubscribeSolanaDexTokenProfilesParams
    from .unsubscribe_solana_dex_trades_params import UnsubscribeSolanaDexTradesParams
    from .unsubscribe_solana_dex_wallet_profiles_params import UnsubscribeSolanaDexWalletProfilesParams
_dynamic_imports: typing.Dict[str, str] = {
    "SubscribeSolanaDexPositionProfilesParams": ".subscribe_solana_dex_position_profiles_params",
    "SubscribeSolanaDexPricesParams": ".subscribe_solana_dex_prices_params",
    "SubscribeSolanaDexSwapsParams": ".subscribe_solana_dex_swaps_params",
    "SubscribeSolanaDexTokenProfilesParams": ".subscribe_solana_dex_token_profiles_params",
    "SubscribeSolanaDexTradesParams": ".subscribe_solana_dex_trades_params",
    "SubscribeSolanaDexWalletProfilesParams": ".subscribe_solana_dex_wallet_profiles_params",
    "UnsubscribeSolanaDexPositionProfilesParams": ".unsubscribe_solana_dex_position_profiles_params",
    "UnsubscribeSolanaDexPricesParams": ".unsubscribe_solana_dex_prices_params",
    "UnsubscribeSolanaDexSwapsParams": ".unsubscribe_solana_dex_swaps_params",
    "UnsubscribeSolanaDexTokenProfilesParams": ".unsubscribe_solana_dex_token_profiles_params",
    "UnsubscribeSolanaDexTradesParams": ".unsubscribe_solana_dex_trades_params",
    "UnsubscribeSolanaDexWalletProfilesParams": ".unsubscribe_solana_dex_wallet_profiles_params",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SubscribeSolanaDexPositionProfilesParams",
    "SubscribeSolanaDexPricesParams",
    "SubscribeSolanaDexSwapsParams",
    "SubscribeSolanaDexTokenProfilesParams",
    "SubscribeSolanaDexTradesParams",
    "SubscribeSolanaDexWalletProfilesParams",
    "UnsubscribeSolanaDexPositionProfilesParams",
    "UnsubscribeSolanaDexPricesParams",
    "UnsubscribeSolanaDexSwapsParams",
    "UnsubscribeSolanaDexTokenProfilesParams",
    "UnsubscribeSolanaDexTradesParams",
    "UnsubscribeSolanaDexWalletProfilesParams",
]
