# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SubscribeEvmDexPoolsParams(UniversalBaseModel):
    chain_id: int = pydantic.Field()
    """
    Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
    """

    pool_addresses: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The pool addresses to filter by. Unlike the other EVM subscriptions, an empty list
    matches no pools rather than all of them, so at least one address is required to
    receive updates.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
