# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SubscribeSolanaDexWalletProfilesParams(UniversalBaseModel):
    wallet_addresses: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The wallet addresses to filter by. Leave empty to subscribe to all wallets.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
