# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SubscribeEvmDexWalletProfilesParams(UniversalBaseModel):
    chain_id: int = pydantic.Field()
    """
    Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
    """

    wallet_addresses: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The wallet addresses to filter by. Leave empty to subscribe to all wallets on the chain.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
