# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .subscribe_token_swaps import SubscribeTokenSwaps
    from .subscribe_token_swaps_params import SubscribeTokenSwapsParams
    from .subscribe_wallet_swaps import SubscribeWalletSwaps
    from .subscribe_wallet_swaps_params import SubscribeWalletSwapsParams
    from .token_swaps_subscription_message import TokenSwapsSubscriptionMessage
    from .token_swaps_subscription_message_data import TokenSwapsSubscriptionMessageData
    from .token_swaps_subscription_message_data_swap_type import TokenSwapsSubscriptionMessageDataSwapType
    from .unsubscribe_token_swaps import UnsubscribeTokenSwaps
    from .unsubscribe_token_swaps_params import UnsubscribeTokenSwapsParams
    from .unsubscribe_wallet_swaps import UnsubscribeWalletSwaps
    from .unsubscribe_wallet_swaps_params import UnsubscribeWalletSwapsParams
    from .wallet_swaps_subscription_message import WalletSwapsSubscriptionMessage
    from .wallet_swaps_subscription_message_data import WalletSwapsSubscriptionMessageData
    from .wallet_swaps_subscription_message_data_swap_type import WalletSwapsSubscriptionMessageDataSwapType
_dynamic_imports: typing.Dict[str, str] = {
    "SubscribeTokenSwaps": ".subscribe_token_swaps",
    "SubscribeTokenSwapsParams": ".subscribe_token_swaps_params",
    "SubscribeWalletSwaps": ".subscribe_wallet_swaps",
    "SubscribeWalletSwapsParams": ".subscribe_wallet_swaps_params",
    "TokenSwapsSubscriptionMessage": ".token_swaps_subscription_message",
    "TokenSwapsSubscriptionMessageData": ".token_swaps_subscription_message_data",
    "TokenSwapsSubscriptionMessageDataSwapType": ".token_swaps_subscription_message_data_swap_type",
    "UnsubscribeTokenSwaps": ".unsubscribe_token_swaps",
    "UnsubscribeTokenSwapsParams": ".unsubscribe_token_swaps_params",
    "UnsubscribeWalletSwaps": ".unsubscribe_wallet_swaps",
    "UnsubscribeWalletSwapsParams": ".unsubscribe_wallet_swaps_params",
    "WalletSwapsSubscriptionMessage": ".wallet_swaps_subscription_message",
    "WalletSwapsSubscriptionMessageData": ".wallet_swaps_subscription_message_data",
    "WalletSwapsSubscriptionMessageDataSwapType": ".wallet_swaps_subscription_message_data_swap_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SubscribeTokenSwaps",
    "SubscribeTokenSwapsParams",
    "SubscribeWalletSwaps",
    "SubscribeWalletSwapsParams",
    "TokenSwapsSubscriptionMessage",
    "TokenSwapsSubscriptionMessageData",
    "TokenSwapsSubscriptionMessageDataSwapType",
    "UnsubscribeTokenSwaps",
    "UnsubscribeTokenSwapsParams",
    "UnsubscribeWalletSwaps",
    "UnsubscribeWalletSwapsParams",
    "WalletSwapsSubscriptionMessage",
    "WalletSwapsSubscriptionMessageData",
    "WalletSwapsSubscriptionMessageDataSwapType",
]
