# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ..core.serialization import FieldMetadata


class SolanaDexProfileSearchPayloadFilter(UniversalBaseModel):
    """
    Conditions that a profile must satisfy to be included in the results.
    Each key is either a field path paired with comparison operators, or a logical operator (`$and`, `$or`) that combines nested filter objects.
    """

    and_: typing_extensions.Annotated[
        typing.Optional[typing.List["SolanaDexProfileSearchPayloadFilter"]],
        FieldMetadata(alias="$and"),
        pydantic.Field(alias="$and", description="Logical AND. A profile must satisfy every nested filter to match."),
    ] = None
    or_: typing_extensions.Annotated[
        typing.Optional[typing.List["SolanaDexProfileSearchPayloadFilter"]],
        FieldMetadata(alias="$or"),
        pydantic.Field(
            alias="$or", description="Logical OR. A profile must satisfy at least one nested filter to match."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(SolanaDexProfileSearchPayloadFilter)
