# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SolanaDexTokenProfileMetadata(UniversalBaseModel):
    last_trade_at: typing.Optional[dt.datetime] = None
    created_at: typing.Optional[dt.datetime] = None
    symbol: typing.Optional[str] = None
    name: typing.Optional[str] = None
    image: typing.Optional[str] = None
    verified: typing.Optional[bool] = None
    creator_address: typing.Optional[str] = None
    twitter: typing.Optional[str] = None
    discord: typing.Optional[str] = None
    website: typing.Optional[str] = None
    telegram: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
