# This file was auto-generated by Fern from our API Definition.

import typing

SolanaDexSwapTypeEnum = typing.Union[
    typing.Literal["quote_token", "token_quote", "token_token", "quote_quote"], typing.Any
]
