# This file was auto-generated by Fern from our API Definition.

import typing

SolanaDexWalletProfileSearchPayloadQueryTargetsEnum = typing.Union[
    typing.Literal["wallet_address", "identity.name", "identity.twitter_username", "identity.telegram_username"],
    typing.Any,
]
