# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SolanaDexTokenProfileMetrics(UniversalBaseModel):
    largest_trade_win: typing.Optional[float] = None
    largest_trade_loss: typing.Optional[float] = None
    avg_buy_size: typing.Optional[float] = None
    avg_sell_size: typing.Optional[float] = None
    avg_price: typing.Optional[float] = None
    avg_buy_price: typing.Optional[float] = None
    avg_sell_price: typing.Optional[float] = None
    avg_buy_mcap: typing.Optional[float] = None
    avg_sell_mcap: typing.Optional[float] = None
    avg_holding_duration: typing.Optional[int] = None
    avg_trade_pnl: typing.Optional[float] = None
    avg_trade_roi: typing.Optional[float] = None
    avg_wallet_winrate: typing.Optional[float] = None
    avg_wallet_pnl: typing.Optional[float] = None
    avg_wallet_roi: typing.Optional[float] = None
    wallet_roi_distribution: typing.Optional[typing.Dict[str, int]] = None
    makers_count: typing.Optional[int] = None
    buyers_count: typing.Optional[int] = None
    sellers_count: typing.Optional[int] = None
    buy_count: typing.Optional[int] = None
    sell_count: typing.Optional[int] = None
    win_position_count: typing.Optional[int] = None
    loss_position_count: typing.Optional[int] = None
    win_pnl: typing.Optional[float] = None
    loss_pnl: typing.Optional[float] = None
    buy_volume: typing.Optional[float] = None
    sell_volume: typing.Optional[float] = None
    pnl: typing.Optional[float] = None
    trade_count: typing.Optional[int] = None
    volume: typing.Optional[float] = None
    position_count: typing.Optional[int] = None
    volume_weighted_winrate: typing.Optional[float] = None
    volume_weighted_roi: typing.Optional[float] = None
    wallet_hit_ratio: typing.Optional[float] = None
    profit_factor: typing.Optional[float] = None
    win_loss_size_ratio: typing.Optional[float] = None
    pnl_volume_ratio: typing.Optional[float] = None
    price_stability: typing.Optional[float] = None
    price_volatility: typing.Optional[float] = None
    roi_stability: typing.Optional[float] = None
    roi_volatility: typing.Optional[float] = None
    pnl_volatility: typing.Optional[float] = None
    pnl_stability: typing.Optional[float] = None
    sharpe_ratio: typing.Optional[float] = None
    sortino_ratio: typing.Optional[float] = None
    max_drawdown: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
