# This file was auto-generated by Fern from our API Definition.

import typing

SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum = typing.Union[
    typing.Literal["token_address", "metadata.name", "metadata.symbol"], typing.Any
]
