# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ...types.evm_dex_position_profile import EvmDexPositionProfile
from ...types.evm_dex_position_profile_payload_options import EvmDexPositionProfilePayloadOptions
from ...types.evm_dex_price import EvmDexPrice
from ...types.evm_dex_price_candle import EvmDexPriceCandle
from ...types.evm_dex_price_history import EvmDexPriceHistory
from ...types.evm_dex_price_stats import EvmDexPriceStats
from ...types.evm_dex_profile_search_payload_filter import EvmDexProfileSearchPayloadFilter
from ...types.evm_dex_profile_search_payload_sort import EvmDexProfileSearchPayloadSort
from ...types.evm_dex_token_profile import EvmDexTokenProfile
from ...types.evm_dex_token_profile_payload_options import EvmDexTokenProfilePayloadOptions
from ...types.evm_dex_token_profile_search_payload_query_field import EvmDexTokenProfileSearchPayloadQueryField
from ...types.evm_dex_wallet_profile import EvmDexWalletProfile
from ...types.evm_dex_wallet_profile_payload_options import EvmDexWalletProfilePayloadOptions
from ...types.evm_dex_wallet_profile_search_payload_query import EvmDexWalletProfileSearchPayloadQuery
from .raw_client import AsyncRawDexClient, RawDexClient
from .types.get_swaps_dex_response import GetSwapsDexResponse
from .types.get_trades_dex_response import GetTradesDexResponse
from .types.search_position_profiles_dex_response import SearchPositionProfilesDexResponse
from .types.search_token_profiles_dex_response import SearchTokenProfilesDexResponse
from .types.search_wallet_profiles_dex_response import SearchWalletProfilesDexResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DexClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDexClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDexClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDexClient
        """
        return self._raw_client

    def get_wallet_profile(
        self,
        *,
        chain_id: int,
        wallet: str,
        options: typing.Optional[EvmDexWalletProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvmDexWalletProfile:
        """
        Returns a wallet profile for a specific wallet.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : str
            Wallet address to retrieve the profile for.

        options : typing.Optional[EvmDexWalletProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvmDexWalletProfile
            Wallet profile for the specified wallet.

        Examples
        --------
        from prism import Client
        from prism.api import EvmDexWalletProfilePayloadOptions

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_wallet_profile(
            chain_id=1,
            wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            options=EvmDexWalletProfilePayloadOptions(
                include_metadata=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.get_wallet_profile(
            chain_id=chain_id, wallet=wallet, options=options, request_options=request_options
        )
        return _response.data

    def search_wallet_profiles(
        self,
        *,
        chain_id: int,
        query: typing.Optional[EvmDexWalletProfileSearchPayloadQuery] = OMIT,
        filter: typing.Optional[EvmDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[EvmDexProfileSearchPayloadSort] = OMIT,
        options: typing.Optional[EvmDexWalletProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchWalletProfilesDexResponse:
        """
        Filter, query, and sort wallet profiles based on specified metrics and conditions.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        query : typing.Optional[EvmDexWalletProfileSearchPayloadQuery]

        filter : typing.Optional[EvmDexProfileSearchPayloadFilter]

        sort : typing.Optional[EvmDexProfileSearchPayloadSort]

        options : typing.Optional[EvmDexWalletProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchWalletProfilesDexResponse
            List of wallet profiles found from the search.

        Examples
        --------
        from prism import Client
        from prism.api import (
            EvmDexProfileSearchPayloadSort,
            EvmDexWalletProfilePayloadOptions,
            EvmDexWalletProfileSearchPayloadQuery,
        )

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.search_wallet_profiles(
            limit=10,
            chain_id=1,
            query=EvmDexWalletProfileSearchPayloadQuery(
                text="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                fields=["wallet_address"],
            ),
            sort=EvmDexProfileSearchPayloadSort(
                field="metrics.7d.cumulative_pnl",
                direction="desc",
            ),
            options=EvmDexWalletProfilePayloadOptions(
                include_metadata=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.search_wallet_profiles(
            chain_id=chain_id,
            query=query,
            filter=filter,
            sort=sort,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def get_token_profile(
        self,
        *,
        chain_id: int,
        token: str,
        options: typing.Optional[EvmDexTokenProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvmDexTokenProfile:
        """
        Returns the profile for a specific token.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        token : str
            Token address to retrieve the profile for.

        options : typing.Optional[EvmDexTokenProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvmDexTokenProfile
            Profile for the specified token.

        Examples
        --------
        from prism import Client
        from prism.api import EvmDexTokenProfilePayloadOptions

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_token_profile(
            chain_id=1,
            token="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            options=EvmDexTokenProfilePayloadOptions(
                include_metadata=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.get_token_profile(
            chain_id=chain_id, token=token, options=options, request_options=request_options
        )
        return _response.data

    def search_token_profiles(
        self,
        *,
        chain_id: int,
        query: typing.Optional[EvmDexTokenProfileSearchPayloadQueryField] = OMIT,
        filter: typing.Optional[EvmDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[EvmDexProfileSearchPayloadSort] = OMIT,
        options: typing.Optional[EvmDexTokenProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchTokenProfilesDexResponse:
        """
        Filter, query, and sort token profiles based on specified metrics and conditions.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        query : typing.Optional[EvmDexTokenProfileSearchPayloadQueryField]

        filter : typing.Optional[EvmDexProfileSearchPayloadFilter]

        sort : typing.Optional[EvmDexProfileSearchPayloadSort]

        options : typing.Optional[EvmDexTokenProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchTokenProfilesDexResponse
            List of filtered and sorted token profiles.

        Examples
        --------
        from prism import Client
        from prism.api import (
            EvmDexProfileSearchPayloadSort,
            EvmDexTokenProfilePayloadOptions,
            EvmDexTokenProfileSearchPayloadQueryField,
        )

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.search_token_profiles(
            limit=10,
            chain_id=1,
            query=EvmDexTokenProfileSearchPayloadQueryField(
                text="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
                fields=["token_address"],
            ),
            sort=EvmDexProfileSearchPayloadSort(
                field="metrics.1d.usd_volume",
                direction="desc",
            ),
            options=EvmDexTokenProfilePayloadOptions(
                include_metadata=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.search_token_profiles(
            chain_id=chain_id,
            query=query,
            filter=filter,
            sort=sort,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def get_position_profile(
        self,
        *,
        chain_id: int,
        wallet: str,
        token: str,
        options: typing.Optional[EvmDexPositionProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvmDexPositionProfile:
        """
        Returns a position profile for a specific wallet-token pair.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : str
            Wallet address of the position to retrieve.

        token : str
            Token address of the position to retrieve.

        options : typing.Optional[EvmDexPositionProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvmDexPositionProfile
            Position profile for the specified wallet-token pair.

        Examples
        --------
        from prism import Client
        from prism.api import EvmDexPositionProfilePayloadOptions

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_position_profile(
            chain_id=1,
            wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            token="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            options=EvmDexPositionProfilePayloadOptions(
                include_metadata=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.get_position_profile(
            chain_id=chain_id, wallet=wallet, token=token, options=options, request_options=request_options
        )
        return _response.data

    def search_position_profiles(
        self,
        *,
        chain_id: int,
        filter: typing.Optional[EvmDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[EvmDexProfileSearchPayloadSort] = OMIT,
        options: typing.Optional[EvmDexPositionProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchPositionProfilesDexResponse:
        """
        Filter, query, and sort position profiles based on specified metrics and conditions.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        filter : typing.Optional[EvmDexProfileSearchPayloadFilter]

        sort : typing.Optional[EvmDexProfileSearchPayloadSort]

        options : typing.Optional[EvmDexPositionProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchPositionProfilesDexResponse
            List of position profiles found from the search.

        Examples
        --------
        from prism import Client
        from prism.api import (
            EvmDexPositionProfilePayloadOptions,
            EvmDexProfileSearchPayloadSort,
        )

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.search_position_profiles(
            limit=10,
            chain_id=1,
            sort=EvmDexProfileSearchPayloadSort(
                field="metrics.7d.pnl",
                direction="desc",
            ),
            options=EvmDexPositionProfilePayloadOptions(
                include_metadata=True,
                include_metrics=["7d"],
            ),
        )
        """
        _response = self._raw_client.search_position_profiles(
            chain_id=chain_id,
            filter=filter,
            sort=sort,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def get_trades(
        self,
        *,
        chain_id: int,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetTradesDexResponse:
        """
        Returns trades for a wallet and/or token on a single chain.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : typing.Optional[str]
            Wallet address to filter trades by.

        token : typing.Optional[str]
            Token address to filter trades by.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTradesDexResponse
            List of trades.

        Examples
        --------
        from prism import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_trades(
            limit=20,
            chain_id=1,
            wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        )
        """
        _response = self._raw_client.get_trades(
            chain_id=chain_id, wallet=wallet, token=token, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def get_swaps(
        self,
        *,
        chain_id: int,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        pool: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSwapsDexResponse:
        """
        Returns swaps for a combination of wallet, token and/or pool.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : typing.Optional[str]
            Wallet address to filter swaps by.

        token : typing.Optional[str]
            Token address to filter swaps by.

        pool : typing.Optional[str]
            Pool address to filter swaps by.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSwapsDexResponse
            List of swaps.

        Examples
        --------
        from prism import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_swaps(
            limit=20,
            chain_id=1,
            wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        )
        """
        _response = self._raw_client.get_swaps(
            chain_id=chain_id,
            wallet=wallet,
            token=token,
            pool=pool,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def get_price(
        self,
        *,
        chain_id: int,
        tokens: typing.Optional[typing.Sequence[str]] = OMIT,
        pools: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPrice]:
        """
        Returns prices for one or more tokens or pools.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        tokens : typing.Optional[typing.Sequence[str]]
            Token addresses to retrieve the latest prices for.

        pools : typing.Optional[typing.Sequence[str]]
            Pool addresses to retrieve the latest prices for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPrice]
            List of token prices for the specified tokens.

        Examples
        --------
        from prism import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_price(
            chain_id=1,
            tokens=["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
        )
        """
        _response = self._raw_client.get_price(
            chain_id=chain_id, tokens=tokens, pools=pools, request_options=request_options
        )
        return _response.data

    def get_price_stats(
        self,
        *,
        chain_id: int,
        tokens: typing.Optional[typing.Sequence[str]] = OMIT,
        pools: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPriceStats]:
        """
        Returns price stats for one or more tokens or pools.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        tokens : typing.Optional[typing.Sequence[str]]
            Token addresses to retrieve price statistics for.

        pools : typing.Optional[typing.Sequence[str]]
            Pool addresses to retrieve price statistics for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPriceStats]
            List of price stats for the specified tokens.

        Examples
        --------
        from prism import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_price_stats(
            chain_id=1,
            tokens=["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
        )
        """
        _response = self._raw_client.get_price_stats(
            chain_id=chain_id, tokens=tokens, pools=pools, request_options=request_options
        )
        return _response.data

    def get_price_candles(
        self,
        *,
        chain_id: int,
        interval: int,
        token: typing.Optional[str] = OMIT,
        pool: typing.Optional[str] = OMIT,
        from_: typing.Optional[dt.datetime] = OMIT,
        to: typing.Optional[dt.datetime] = OMIT,
        count: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPriceCandle]:
        """
        Returns price candles for a specific token and/or pool.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        interval : int
            Sampling interval between data points, in seconds.

        token : typing.Optional[str]
            Token address to filter by.

        pool : typing.Optional[str]
            Pool address to filter by.

        from_ : typing.Optional[dt.datetime]
            Start of the candle range, as a date-time RFC3339 string.
            Can be combined with `to` to define a bounded range.

        to : typing.Optional[dt.datetime]
            End of the candle range, as a date-time RFC3339 string.
            Defaults to the current time.

        count : typing.Optional[int]
            Number of candles to return.
            Must be combined with `from` or `to`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPriceCandle]
            Price candles for the specified token.

        Examples
        --------
        import datetime

        from prism import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_price_candles(
            chain_id=1,
            token="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            from_=datetime.datetime.fromisoformat(
                "2026-04-27 00:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2026-04-27 01:00:00+00:00",
            ),
            interval=60,
        )
        """
        _response = self._raw_client.get_price_candles(
            chain_id=chain_id,
            interval=interval,
            token=token,
            pool=pool,
            from_=from_,
            to=to,
            count=count,
            request_options=request_options,
        )
        return _response.data

    def get_price_history(
        self,
        *,
        chain_id: int,
        from_: dt.datetime,
        interval: int,
        tokens: typing.Optional[typing.Sequence[str]] = OMIT,
        pools: typing.Optional[typing.Sequence[str]] = OMIT,
        to: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPriceHistory]:
        """
        Returns price history for one or more tokens or pools.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        from_ : dt.datetime
            Start of the history range, as a date-time RFC3339 string.

        interval : int
            Sampling interval between data points, in seconds.

        tokens : typing.Optional[typing.Sequence[str]]
            Token addresses to retrieve price history for.

        pools : typing.Optional[typing.Sequence[str]]
            Pool addresses to retrieve price history for.

        to : typing.Optional[dt.datetime]
            End of the history range, as a date-time RFC3339 string.
            Defaults to the current time.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPriceHistory]
            Price history for the specified tokens.

        Examples
        --------
        import datetime

        from prism import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.api.evm.dex.get_price_history(
            chain_id=1,
            tokens=["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
            from_=datetime.datetime.fromisoformat(
                "2026-04-27 00:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2026-04-27 01:00:00+00:00",
            ),
            interval=3600,
        )
        """
        _response = self._raw_client.get_price_history(
            chain_id=chain_id,
            from_=from_,
            interval=interval,
            tokens=tokens,
            pools=pools,
            to=to,
            request_options=request_options,
        )
        return _response.data


class AsyncDexClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDexClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDexClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDexClient
        """
        return self._raw_client

    async def get_wallet_profile(
        self,
        *,
        chain_id: int,
        wallet: str,
        options: typing.Optional[EvmDexWalletProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvmDexWalletProfile:
        """
        Returns a wallet profile for a specific wallet.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : str
            Wallet address to retrieve the profile for.

        options : typing.Optional[EvmDexWalletProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvmDexWalletProfile
            Wallet profile for the specified wallet.

        Examples
        --------
        import asyncio

        from prism import AsyncClient
        from prism.api import EvmDexWalletProfilePayloadOptions

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_wallet_profile(
                chain_id=1,
                wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                options=EvmDexWalletProfilePayloadOptions(
                    include_metadata=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_wallet_profile(
            chain_id=chain_id, wallet=wallet, options=options, request_options=request_options
        )
        return _response.data

    async def search_wallet_profiles(
        self,
        *,
        chain_id: int,
        query: typing.Optional[EvmDexWalletProfileSearchPayloadQuery] = OMIT,
        filter: typing.Optional[EvmDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[EvmDexProfileSearchPayloadSort] = OMIT,
        options: typing.Optional[EvmDexWalletProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchWalletProfilesDexResponse:
        """
        Filter, query, and sort wallet profiles based on specified metrics and conditions.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        query : typing.Optional[EvmDexWalletProfileSearchPayloadQuery]

        filter : typing.Optional[EvmDexProfileSearchPayloadFilter]

        sort : typing.Optional[EvmDexProfileSearchPayloadSort]

        options : typing.Optional[EvmDexWalletProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchWalletProfilesDexResponse
            List of wallet profiles found from the search.

        Examples
        --------
        import asyncio

        from prism import AsyncClient
        from prism.api import (
            EvmDexProfileSearchPayloadSort,
            EvmDexWalletProfilePayloadOptions,
            EvmDexWalletProfileSearchPayloadQuery,
        )

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.search_wallet_profiles(
                limit=10,
                chain_id=1,
                query=EvmDexWalletProfileSearchPayloadQuery(
                    text="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                    fields=["wallet_address"],
                ),
                sort=EvmDexProfileSearchPayloadSort(
                    field="metrics.7d.cumulative_pnl",
                    direction="desc",
                ),
                options=EvmDexWalletProfilePayloadOptions(
                    include_metadata=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_wallet_profiles(
            chain_id=chain_id,
            query=query,
            filter=filter,
            sort=sort,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_token_profile(
        self,
        *,
        chain_id: int,
        token: str,
        options: typing.Optional[EvmDexTokenProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvmDexTokenProfile:
        """
        Returns the profile for a specific token.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        token : str
            Token address to retrieve the profile for.

        options : typing.Optional[EvmDexTokenProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvmDexTokenProfile
            Profile for the specified token.

        Examples
        --------
        import asyncio

        from prism import AsyncClient
        from prism.api import EvmDexTokenProfilePayloadOptions

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_token_profile(
                chain_id=1,
                token="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
                options=EvmDexTokenProfilePayloadOptions(
                    include_metadata=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_token_profile(
            chain_id=chain_id, token=token, options=options, request_options=request_options
        )
        return _response.data

    async def search_token_profiles(
        self,
        *,
        chain_id: int,
        query: typing.Optional[EvmDexTokenProfileSearchPayloadQueryField] = OMIT,
        filter: typing.Optional[EvmDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[EvmDexProfileSearchPayloadSort] = OMIT,
        options: typing.Optional[EvmDexTokenProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchTokenProfilesDexResponse:
        """
        Filter, query, and sort token profiles based on specified metrics and conditions.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        query : typing.Optional[EvmDexTokenProfileSearchPayloadQueryField]

        filter : typing.Optional[EvmDexProfileSearchPayloadFilter]

        sort : typing.Optional[EvmDexProfileSearchPayloadSort]

        options : typing.Optional[EvmDexTokenProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchTokenProfilesDexResponse
            List of filtered and sorted token profiles.

        Examples
        --------
        import asyncio

        from prism import AsyncClient
        from prism.api import (
            EvmDexProfileSearchPayloadSort,
            EvmDexTokenProfilePayloadOptions,
            EvmDexTokenProfileSearchPayloadQueryField,
        )

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.search_token_profiles(
                limit=10,
                chain_id=1,
                query=EvmDexTokenProfileSearchPayloadQueryField(
                    text="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
                    fields=["token_address"],
                ),
                sort=EvmDexProfileSearchPayloadSort(
                    field="metrics.1d.usd_volume",
                    direction="desc",
                ),
                options=EvmDexTokenProfilePayloadOptions(
                    include_metadata=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_token_profiles(
            chain_id=chain_id,
            query=query,
            filter=filter,
            sort=sort,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_position_profile(
        self,
        *,
        chain_id: int,
        wallet: str,
        token: str,
        options: typing.Optional[EvmDexPositionProfilePayloadOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvmDexPositionProfile:
        """
        Returns a position profile for a specific wallet-token pair.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : str
            Wallet address of the position to retrieve.

        token : str
            Token address of the position to retrieve.

        options : typing.Optional[EvmDexPositionProfilePayloadOptions]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvmDexPositionProfile
            Position profile for the specified wallet-token pair.

        Examples
        --------
        import asyncio

        from prism import AsyncClient
        from prism.api import EvmDexPositionProfilePayloadOptions

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_position_profile(
                chain_id=1,
                wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                token="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
                options=EvmDexPositionProfilePayloadOptions(
                    include_metadata=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_position_profile(
            chain_id=chain_id, wallet=wallet, token=token, options=options, request_options=request_options
        )
        return _response.data

    async def search_position_profiles(
        self,
        *,
        chain_id: int,
        filter: typing.Optional[EvmDexProfileSearchPayloadFilter] = OMIT,
        sort: typing.Optional[EvmDexProfileSearchPayloadSort] = OMIT,
        options: typing.Optional[EvmDexPositionProfilePayloadOptions] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchPositionProfilesDexResponse:
        """
        Filter, query, and sort position profiles based on specified metrics and conditions.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        filter : typing.Optional[EvmDexProfileSearchPayloadFilter]

        sort : typing.Optional[EvmDexProfileSearchPayloadSort]

        options : typing.Optional[EvmDexPositionProfilePayloadOptions]

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchPositionProfilesDexResponse
            List of position profiles found from the search.

        Examples
        --------
        import asyncio

        from prism import AsyncClient
        from prism.api import (
            EvmDexPositionProfilePayloadOptions,
            EvmDexProfileSearchPayloadSort,
        )

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.search_position_profiles(
                limit=10,
                chain_id=1,
                sort=EvmDexProfileSearchPayloadSort(
                    field="metrics.7d.pnl",
                    direction="desc",
                ),
                options=EvmDexPositionProfilePayloadOptions(
                    include_metadata=True,
                    include_metrics=["7d"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_position_profiles(
            chain_id=chain_id,
            filter=filter,
            sort=sort,
            options=options,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_trades(
        self,
        *,
        chain_id: int,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetTradesDexResponse:
        """
        Returns trades for a wallet and/or token on a single chain.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : typing.Optional[str]
            Wallet address to filter trades by.

        token : typing.Optional[str]
            Token address to filter trades by.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTradesDexResponse
            List of trades.

        Examples
        --------
        import asyncio

        from prism import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_trades(
                limit=20,
                chain_id=1,
                wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_trades(
            chain_id=chain_id, wallet=wallet, token=token, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def get_swaps(
        self,
        *,
        chain_id: int,
        wallet: typing.Optional[str] = OMIT,
        token: typing.Optional[str] = OMIT,
        pool: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSwapsDexResponse:
        """
        Returns swaps for a combination of wallet, token and/or pool.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        wallet : typing.Optional[str]
            Wallet address to filter swaps by.

        token : typing.Optional[str]
            Token address to filter swaps by.

        pool : typing.Optional[str]
            Pool address to filter swaps by.

        limit : typing.Optional[int]
            Maximum number of results to return in a single page.

        cursor : typing.Optional[str]
            Opaque cursor returned by a previous response. Pass it to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSwapsDexResponse
            List of swaps.

        Examples
        --------
        import asyncio

        from prism import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_swaps(
                limit=20,
                chain_id=1,
                wallet="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_swaps(
            chain_id=chain_id,
            wallet=wallet,
            token=token,
            pool=pool,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_price(
        self,
        *,
        chain_id: int,
        tokens: typing.Optional[typing.Sequence[str]] = OMIT,
        pools: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPrice]:
        """
        Returns prices for one or more tokens or pools.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        tokens : typing.Optional[typing.Sequence[str]]
            Token addresses to retrieve the latest prices for.

        pools : typing.Optional[typing.Sequence[str]]
            Pool addresses to retrieve the latest prices for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPrice]
            List of token prices for the specified tokens.

        Examples
        --------
        import asyncio

        from prism import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_price(
                chain_id=1,
                tokens=["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price(
            chain_id=chain_id, tokens=tokens, pools=pools, request_options=request_options
        )
        return _response.data

    async def get_price_stats(
        self,
        *,
        chain_id: int,
        tokens: typing.Optional[typing.Sequence[str]] = OMIT,
        pools: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPriceStats]:
        """
        Returns price stats for one or more tokens or pools.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        tokens : typing.Optional[typing.Sequence[str]]
            Token addresses to retrieve price statistics for.

        pools : typing.Optional[typing.Sequence[str]]
            Pool addresses to retrieve price statistics for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPriceStats]
            List of price stats for the specified tokens.

        Examples
        --------
        import asyncio

        from prism import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_price_stats(
                chain_id=1,
                tokens=["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price_stats(
            chain_id=chain_id, tokens=tokens, pools=pools, request_options=request_options
        )
        return _response.data

    async def get_price_candles(
        self,
        *,
        chain_id: int,
        interval: int,
        token: typing.Optional[str] = OMIT,
        pool: typing.Optional[str] = OMIT,
        from_: typing.Optional[dt.datetime] = OMIT,
        to: typing.Optional[dt.datetime] = OMIT,
        count: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPriceCandle]:
        """
        Returns price candles for a specific token and/or pool.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        interval : int
            Sampling interval between data points, in seconds.

        token : typing.Optional[str]
            Token address to filter by.

        pool : typing.Optional[str]
            Pool address to filter by.

        from_ : typing.Optional[dt.datetime]
            Start of the candle range, as a date-time RFC3339 string.
            Can be combined with `to` to define a bounded range.

        to : typing.Optional[dt.datetime]
            End of the candle range, as a date-time RFC3339 string.
            Defaults to the current time.

        count : typing.Optional[int]
            Number of candles to return.
            Must be combined with `from` or `to`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPriceCandle]
            Price candles for the specified token.

        Examples
        --------
        import asyncio
        import datetime

        from prism import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_price_candles(
                chain_id=1,
                token="0x6982508145454Ce325dDbE47a25d4ec3d2311933",
                from_=datetime.datetime.fromisoformat(
                    "2026-04-27 00:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2026-04-27 01:00:00+00:00",
                ),
                interval=60,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price_candles(
            chain_id=chain_id,
            interval=interval,
            token=token,
            pool=pool,
            from_=from_,
            to=to,
            count=count,
            request_options=request_options,
        )
        return _response.data

    async def get_price_history(
        self,
        *,
        chain_id: int,
        from_: dt.datetime,
        interval: int,
        tokens: typing.Optional[typing.Sequence[str]] = OMIT,
        pools: typing.Optional[typing.Sequence[str]] = OMIT,
        to: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[EvmDexPriceHistory]:
        """
        Returns price history for one or more tokens or pools.

        Parameters
        ----------
        chain_id : int
            Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).

        from_ : dt.datetime
            Start of the history range, as a date-time RFC3339 string.

        interval : int
            Sampling interval between data points, in seconds.

        tokens : typing.Optional[typing.Sequence[str]]
            Token addresses to retrieve price history for.

        pools : typing.Optional[typing.Sequence[str]]
            Pool addresses to retrieve price history for.

        to : typing.Optional[dt.datetime]
            End of the history range, as a date-time RFC3339 string.
            Defaults to the current time.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EvmDexPriceHistory]
            Price history for the specified tokens.

        Examples
        --------
        import asyncio
        import datetime

        from prism import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api.evm.dex.get_price_history(
                chain_id=1,
                tokens=["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
                from_=datetime.datetime.fromisoformat(
                    "2026-04-27 00:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2026-04-27 01:00:00+00:00",
                ),
                interval=3600,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_price_history(
            chain_id=chain_id,
            from_=from_,
            interval=interval,
            tokens=tokens,
            pools=pools,
            to=to,
            request_options=request_options,
        )
        return _response.data
