# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....types.paginated_response import PaginatedResponse
from ....types.solana_dex_wallet_profile import SolanaDexWalletProfile


class SearchWalletProfilesDexResponse(PaginatedResponse):
    data: typing.Optional[typing.List[SolanaDexWalletProfile]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
