# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class ApiClientEnvironment:
    DEFAULT: ApiClientEnvironment

    def __init__(self, *, base: str, production: str, development: str):
        self.base = base
        self.production = production
        self.development = development


ApiClientEnvironment.DEFAULT = ApiClientEnvironment(
    base="https://refract.prismapi.io",
    production="wss://refract.prismapi.io",
    development="wss://refract-dev.prismapi.io",
)
